//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyFox.Ui.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyFox.Ui.Resources.Strings.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountNameLabel {
            get {
                return ResourceManager.GetString("AccountNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Account..
        /// </summary>
        public static string AccountRequiredMessage {
            get {
                return ResourceManager.GetString("AccountRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsTitle {
            get {
                return ResourceManager.GetString("AccountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your Accounts.
        /// </summary>
        public static string AccountsToolTip {
            get {
                return ResourceManager.GetString("AccountsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string AddAccountLabel {
            get {
                return ResourceManager.GetString("AddAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string AddAccountTitle {
            get {
                return ResourceManager.GetString("AddAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Budget.
        /// </summary>
        public static string AddBudgetLabel {
            get {
                return ResourceManager.GetString("AddBudgetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Budget.
        /// </summary>
        public static string AddBudgetTitle {
            get {
                return ResourceManager.GetString("AddBudgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategoryLabel {
            get {
                return ResourceManager.GetString("AddCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategoryTitle {
            get {
                return ResourceManager.GetString("AddCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Expense.
        /// </summary>
        public static string AddExpenseTitle {
            get {
                return ResourceManager.GetString("AddExpenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Income.
        /// </summary>
        public static string AddIncomeTitle {
            get {
                return ResourceManager.GetString("AddIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Payment.
        /// </summary>
        public static string AddPaymentLabel {
            get {
                return ResourceManager.GetString("AddPaymentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Payment.
        /// </summary>
        public static string AddPaymentTitle {
            get {
                return ResourceManager.GetString("AddPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Payment with details.
        /// </summary>
        public static string AddPaymentToolTip {
            get {
                return ResourceManager.GetString("AddPaymentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Transfer.
        /// </summary>
        public static string AddTransferTitle {
            get {
                return ResourceManager.GetString("AddTransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllLabel {
            get {
                return ResourceManager.GetString("AllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount may not be negative. If it is subtracted or added is deteremined by the kind of payment you create..
        /// </summary>
        public static string AmountMayNotBeNegativeMessage {
            get {
                return ResourceManager.GetString("AmountMayNotBeNegativeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative amount.
        /// </summary>
        public static string AmountMayNotBeNegativeTitle {
            get {
                return ResourceManager.GetString("AmountMayNotBeNegativeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A note for payment is required.
        /// </summary>
        public static string ANoteForPaymentIsRequired {
            get {
                return ResourceManager.GetString("ANoteForPaymentIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filter.
        /// </summary>
        public static string ApplyFilterLabel {
            get {
                return ResourceManager.GetString("ApplyFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string AssetsLabel {
            get {
                return ResourceManager.GetString("AssetsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        public static string AuthenticationFailedTitle {
            get {
                return ResourceManager.GetString("AuthenticationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you activate this setting we backup your data automatically to OneDrive. Also we check periodically if something changed on another device..
        /// </summary>
        public static string AutobackupInformationLabel {
            get {
                return ResourceManager.GetString("AutobackupInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically upload and download backups.
        /// </summary>
        public static string AutobackupLabel {
            get {
                return ResourceManager.GetString("AutobackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autobackup.
        /// </summary>
        public static string AutobackupTitle {
            get {
                return ResourceManager.GetString("AutobackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackLabel {
            get {
                return ResourceManager.GetString("BackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup created successfully.
        /// </summary>
        public static string BackupCreatedMessage {
            get {
                return ResourceManager.GetString("BackupCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup failed!.
        /// </summary>
        public static string BackupFailedTitle {
            get {
                return ResourceManager.GetString("BackupFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data will be saved to your OneDrive Account. You’ll find them in the Application Folder in a new folder called &quot;MoneyFox&quot;..
        /// </summary>
        public static string BackupInformationLabel {
            get {
                return ResourceManager.GetString("BackupInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup restored successfully..
        /// </summary>
        public static string BackupRestoredMessage {
            get {
                return ResourceManager.GetString("BackupRestoredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string BackupTitle {
            get {
                return ResourceManager.GetString("BackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup your information.
        /// </summary>
        public static string BackupToolTip {
            get {
                return ResourceManager.GetString("BackupToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload of backup skipped, since remote version was already up to date..
        /// </summary>
        public static string BackupUploadSkippedMessage {
            get {
                return ResourceManager.GetString("BackupUploadSkippedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biannually.
        /// </summary>
        public static string BiannuallyLabel {
            get {
                return ResourceManager.GetString("BiannuallyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bimonthly.
        /// </summary>
        public static string BimonthlyLabel {
            get {
                return ResourceManager.GetString("BimonthlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biweekly.
        /// </summary>
        public static string BiweeklyLabel {
            get {
                return ResourceManager.GetString("BiweeklyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Name.
        /// </summary>
        public static string BudgetNameLabel {
            get {
                return ResourceManager.GetString("BudgetNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budgets.
        /// </summary>
        public static string BudgetsLabel {
            get {
                return ResourceManager.GetString("BudgetsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budgets.
        /// </summary>
        public static string BudgetsTitle {
            get {
                return ResourceManager.GetString("BudgetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string CanceledTitle {
            get {
                return ResourceManager.GetString("CanceledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income, expenses and gains for the selected time period..
        /// </summary>
        public static string CashflowDescription {
            get {
                return ResourceManager.GetString("CashflowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashflow.
        /// </summary>
        public static string CashflowLabel {
            get {
                return ResourceManager.GetString("CashflowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow.
        /// </summary>
        public static string CashFlowStatisticTitle {
            get {
                return ResourceManager.GetString("CashFlowStatisticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories can help order your payments. Also they make it easier to analyze your spendings and incomes in the statistics..
        /// </summary>
        public static string CategorieIntroductionText {
            get {
                return ResourceManager.GetString("CategorieIntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreading of the expenses to the categories..
        /// </summary>
        public static string CategorieSpreadingDescription {
            get {
                return ResourceManager.GetString("CategorieSpreadingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesTitle {
            get {
                return ResourceManager.GetString("CategoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your Categories.
        /// </summary>
        public static string CategoriesToolTip {
            get {
                return ResourceManager.GetString("CategoriesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryNameLabel {
            get {
                return ResourceManager.GetString("CategoryNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the progression of a category by month..
        /// </summary>
        public static string CategoryProgressionDescription {
            get {
                return ResourceManager.GetString("CategoryProgressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Progression.
        /// </summary>
        public static string CategoryProgressionLabel {
            get {
                return ResourceManager.GetString("CategoryProgressionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Progression.
        /// </summary>
        public static string CategoryProgressionTitle {
            get {
                return ResourceManager.GetString("CategoryProgressionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Spreading.
        /// </summary>
        public static string CategorySpreadingLabel {
            get {
                return ResourceManager.GetString("CategorySpreadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Spreading.
        /// </summary>
        public static string CategorySpreadingTitle {
            get {
                return ResourceManager.GetString("CategorySpreadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of the categories with a Payment..
        /// </summary>
        public static string CategorySummaryDescription {
            get {
                return ResourceManager.GetString("CategorySummaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Summary.
        /// </summary>
        public static string CategorySummaryLabel {
            get {
                return ResourceManager.GetString("CategorySummaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payments in the selected time range found..
        /// </summary>
        public static string CategorySummaryPlaceholder {
            get {
                return ResourceManager.GetString("CategorySummaryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Summary.
        /// </summary>
        public static string CategorySummaryTitle {
            get {
                return ResourceManager.GetString("CategorySummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charged Account.
        /// </summary>
        public static string ChargedAccountLabel {
            get {
                return ResourceManager.GetString("ChargedAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared.
        /// </summary>
        public static string ClearedFilterLabel {
            get {
                return ResourceManager.GetString("ClearedFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s it! You&apos;re set for using the MoneyFox..
        /// </summary>
        public static string CompletedText {
            get {
                return ResourceManager.GetString("CompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string CompletedTitle {
            get {
                return ResourceManager.GetString("CompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string CompleteLabel {
            get {
                return ResourceManager.GetString("CompleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactLabel {
            get {
                return ResourceManager.GetString("ContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see all contributions head over to GitHub:.
        /// </summary>
        public static string ContributerLabel {
            get {
                return ResourceManager.GetString("ContributerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributions.
        /// </summary>
        public static string ContributionsLabel {
            get {
                return ResourceManager.GetString("ContributionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account Now.
        /// </summary>
        public static string CreateAccountNowLabel {
            get {
                return ResourceManager.GetString("CreateAccountNowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Backup.
        /// </summary>
        public static string CreateBackupLabel {
            get {
                return ResourceManager.GetString("CreateBackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category now.
        /// </summary>
        public static string CreateCategoryNowLabel {
            get {
                return ResourceManager.GetString("CreateCategoryNowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDateHeader {
            get {
                return ResourceManager.GetString("CreationDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date:.
        /// </summary>
        public static string CreationDateLabel {
            get {
                return ResourceManager.GetString("CreationDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date: {0}.
        /// </summary>
        public static string CreationDateTemplateLabel {
            get {
                return ResourceManager.GetString("CreationDateTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the currency you would like to use in the app. This will be used as the default currency for example for accounts, payments and budgets.
        ///You can change this late in the settings..
        /// </summary>
        public static string CurrencyIntroductionText {
            get {
                return ResourceManager.GetString("CurrencyIntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CurrencyIntroductionTitle {
            get {
                return ResourceManager.GetString("CurrencyIntroductionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the currency you would like to use in the app. This will be used as the default currency for example for accounts, payments and budgets..
        /// </summary>
        public static string CurrencySettingText {
            get {
                return ResourceManager.GetString("CurrencySettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance.
        /// </summary>
        public static string CurrentBalanceLabel {
            get {
                return ResourceManager.GetString("CurrentBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string DailyLabel {
            get {
                return ResourceManager.GetString("DailyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily without weekend.
        /// </summary>
        public static string DailyWithoutWeekendLabel {
            get {
                return ResourceManager.GetString("DailyWithoutWeekendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkLabel {
            get {
                return ResourceManager.GetString("DarkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        public static string DateRangeHeader {
            get {
                return ResourceManager.GetString("DateRangeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this Account?.
        /// </summary>
        public static string DeleteAccountConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this budget?.
        /// </summary>
        public static string DeleteBudgetConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteBudgetConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this Category?.
        /// </summary>
        public static string DeleteCategoryConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteCategoryConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this Payment?.
        /// </summary>
        public static string DeletePaymentConfirmationMessage {
            get {
                return ResourceManager.GetString("DeletePaymentConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve deleted a recurring payment. Do you want to delete the recurrence as well?.
        /// </summary>
        public static string DeleteRecurringPaymentMessage {
            get {
                return ResourceManager.GetString("DeleteRecurringPaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Recurrence?.
        /// </summary>
        public static string DeleteRecurringPaymentTitle {
            get {
                return ResourceManager.GetString("DeleteRecurringPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DoneLabel {
            get {
                return ResourceManager.GetString("DoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with that name already exists. Continue with saving?.
        /// </summary>
        public static string DuplicateAccountMessage {
            get {
                return ResourceManager.GetString("DuplicateAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Category with that name already exists..
        /// </summary>
        public static string DuplicateCategoryMessage {
            get {
                return ResourceManager.GetString("DuplicateCategoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already used.
        /// </summary>
        public static string DuplicatedNameTitle {
            get {
                return ResourceManager.GetString("DuplicatedNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        public static string EditAccountTitle {
            get {
                return ResourceManager.GetString("EditAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Budget.
        /// </summary>
        public static string EditBudgetTitle {
            get {
                return ResourceManager.GetString("EditBudgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        public static string EditCategoryTitle {
            get {
                return ResourceManager.GetString("EditCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Income.
        /// </summary>
        public static string EditIncomeTitle {
            get {
                return ResourceManager.GetString("EditIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Payment.
        /// </summary>
        public static string EditPaymentTitle {
            get {
                return ResourceManager.GetString("EditPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Expense.
        /// </summary>
        public static string EditSpendingTitle {
            get {
                return ResourceManager.GetString("EditSpendingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Transfer.
        /// </summary>
        public static string EditTransferTitle {
            get {
                return ResourceManager.GetString("EditTransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EnddateLabel {
            get {
                return ResourceManager.GetString("EnddateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Endless.
        /// </summary>
        public static string EndlessLabel {
            get {
                return ResourceManager.GetString("EndlessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Month.
        /// </summary>
        public static string EndOfMonthBalanceLabel {
            get {
                return ResourceManager.GetString("EndOfMonthBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Of Month:.
        /// </summary>
        public static string EndOfMonthLabel {
            get {
                return ResourceManager.GetString("EndOfMonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during the authentication. Please try again later..
        /// </summary>
        public static string ErrorMessageAuthenticationFailed {
            get {
                return ResourceManager.GetString("ErrorMessageAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Time Range.
        /// </summary>
        public static string EvaluationTimeRangeLabel {
            get {
                return ResourceManager.GetString("EvaluationTimeRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This defines the time range in which payments are included to calculate your monthly average to compare to your spending limit..
        /// </summary>
        public static string EvaluationTimeRangeMessage {
            get {
                return ResourceManager.GetString("EvaluationTimeRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Accounts.
        /// </summary>
        public static string ExcludedAccountsHeader {
            get {
                return ResourceManager.GetString("ExcludedAccountsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense: {0} / Income: {1}.
        /// </summary>
        public static string ExpenseAndIncomeTemplate {
            get {
                return ResourceManager.GetString("ExpenseAndIncomeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add expense.
        /// </summary>
        public static string ExpenseHeader {
            get {
                return ResourceManager.GetString("ExpenseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string ExpenseLabel {
            get {
                return ResourceManager.GetString("ExpenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login to your backup service. Automatic backup upload was disabled. Please login and enable it again..
        /// </summary>
        public static string FailedToLoginToBackupMessage {
            get {
                return ResourceManager.GetString("FailedToLoginToBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed!.
        /// </summary>
        public static string FailedToLoginToBackupTitle {
            get {
                return ResourceManager.GetString("FailedToLoginToBackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback MoneyFox.
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterLabel {
            get {
                return ResourceManager.GetString("FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your local database has a newer modification date than the one on OneDrive. Do you want to override your local data?.
        /// </summary>
        public static string ForceOverrideBackupMessage {
            get {
                return ResourceManager.GetString("ForceOverrideBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Local Data.
        /// </summary>
        public static string ForceOverrideBackupTitle {
            get {
                return ResourceManager.GetString("ForceOverrideBackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gains.
        /// </summary>
        public static string GainsLabel {
            get {
                return ResourceManager.GetString("GainsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        public static string GeneralErrorTitle {
            get {
                return ResourceManager.GetString("GeneralErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Accounts.
        /// </summary>
        public static string GoToAccountsLabel {
            get {
                return ResourceManager.GetString("GoToAccountsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Budgets.
        /// </summary>
        public static string GoToBudgetsLabel {
            get {
                return ResourceManager.GetString("GoToBudgetsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included Accounts.
        /// </summary>
        public static string IncludedAccountsHeader {
            get {
                return ResourceManager.GetString("IncludedAccountsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included Categories.
        /// </summary>
        public static string IncludedCategoriesLabel {
            get {
                return ResourceManager.GetString("IncludedCategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income and Expenses.
        /// </summary>
        public static string IncomeAndExpensesLabel {
            get {
                return ResourceManager.GetString("IncomeAndExpensesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add income.
        /// </summary>
        public static string IncomeHeader {
            get {
                return ResourceManager.GetString("IncomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string IncomeLabel {
            get {
                return ResourceManager.GetString("IncomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income / Expenses:.
        /// </summary>
        public static string IncomeSpendingLabel {
            get {
                return ResourceManager.GetString("IncomeSpendingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gains.
        /// </summary>
        public static string IncreaseLabel {
            get {
                return ResourceManager.GetString("IncreaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoLabel {
            get {
                return ResourceManager.GetString("InfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an open-source project – and we’d love to work with you! Feel free to contribute.
        ///Tap to visit the Repository:.
        /// </summary>
        public static string InfoOpenSource {
            get {
                return ResourceManager.GetString("InfoOpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Balance.
        /// </summary>
        public static string InitialBalanceLabel {
            get {
                return ResourceManager.GetString("InitialBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string IntervalLabel {
            get {
                return ResourceManager.GetString("IntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enddate of a recurring Payment has to be in the future. Please check your input..
        /// </summary>
        public static string InvalidEnddateMessage {
            get {
                return ResourceManager.GetString("InvalidEnddateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid End Date.
        /// </summary>
        public static string InvalidEnddateTitle {
            get {
                return ResourceManager.GetString("InvalidEnddateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current balance seems to be an invalid number. Please check that you haven&apos;t entered any special characters and used the correct separator..
        /// </summary>
        public static string InvalidNumberCurrentBalanceMessage {
            get {
                return ResourceManager.GetString("InvalidNumberCurrentBalanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number.
        /// </summary>
        public static string InvalidNumberTitle {
            get {
                return ResourceManager.GetString("InvalidNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The spending limit has to be larger than zero..
        /// </summary>
        public static string InvalidSpendingLimitMessage {
            get {
                return ResourceManager.GetString("InvalidSpendingLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Spending Limit.
        /// </summary>
        public static string InvalidSpendingLimitTitle {
            get {
                return ResourceManager.GetString("InvalidSpendingLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared.
        /// </summary>
        public static string IsClearedLabel {
            get {
                return ResourceManager.GetString("IsClearedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude account from balance.
        /// </summary>
        public static string IsExcludedLabel {
            get {
                return ResourceManager.GetString("IsExcludedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group List.
        /// </summary>
        public static string IsGroupedLabel {
            get {
                return ResourceManager.GetString("IsGroupedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Recurring.
        /// </summary>
        public static string IsRecurringFilterLabel {
            get {
                return ResourceManager.GetString("IsRecurringFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring.
        /// </summary>
        public static string IsRecurringLabel {
            get {
                return ResourceManager.GetString("IsRecurringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Backup created at:.
        /// </summary>
        public static string LastBackupDateLabel {
            get {
                return ResourceManager.GetString("LastBackupDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Day of Month.
        /// </summary>
        public static string LastDayOfMonthLabel {
            get {
                return ResourceManager.GetString("LastDayOfMonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Five Years.
        /// </summary>
        public static string LastFiveYearsLabel {
            get {
                return ResourceManager.GetString("LastFiveYearsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Three Years.
        /// </summary>
        public static string LastThreeYearsLabel {
            get {
                return ResourceManager.GetString("LastThreeYearsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Two Years.
        /// </summary>
        public static string LastTwoYearsLabel {
            get {
                return ResourceManager.GetString("LastTwoYearsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        public static string LastYearLabel {
            get {
                return ResourceManager.GetString("LastYearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightLabel {
            get {
                return ResourceManager.GetString("LightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingLabel {
            get {
                return ResourceManager.GetString("LoadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loggedin successfully..
        /// </summary>
        public static string LoggedInMessage {
            get {
                return ResourceManager.GetString("LoggedInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in!.
        /// </summary>
        public static string LoggedInTitle {
            get {
                return ResourceManager.GetString("LoggedInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out successfully..
        /// </summary>
        public static string LoggedOutMessage {
            get {
                return ResourceManager.GetString("LoggedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out.
        /// </summary>
        public static string LoggedOutTitle {
            get {
                return ResourceManager.GetString("LoggedOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was canceled..
        /// </summary>
        public static string LoginCanceledMessage {
            get {
                return ResourceManager.GetString("LoginCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed!.
        /// </summary>
        public static string LoginFailedTitle {
            get {
                return ResourceManager.GetString("LoginFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout was canceled..
        /// </summary>
        public static string LogoutCanceledMessage {
            get {
                return ResourceManager.GetString("LogoutCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutLabel {
            get {
                return ResourceManager.GetString("LogoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory field.
        /// </summary>
        public static string MandatoryFieldEmptyTitle {
            get {
                return ResourceManager.GetString("MandatoryFieldEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification Date.
        /// </summary>
        public static string ModificationDateHeader {
            get {
                return ResourceManager.GetString("ModificationDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification Date:.
        /// </summary>
        public static string ModificationDateLabel {
            get {
                return ResourceManager.GetString("ModificationDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification Date: {0}.
        /// </summary>
        public static string ModificationDateTemplateLabel {
            get {
                return ResourceManager.GetString("ModificationDateTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have modified a recurring payment. Do you want to update the recurrence?.
        /// </summary>
        public static string ModifyRecurrenceMessage {
            get {
                return ResourceManager.GetString("ModifyRecurrenceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Recurrence.
        /// </summary>
        public static string ModifyRecurrenceTitle {
            get {
                return ResourceManager.GetString("ModifyRecurrenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string MonthLabel {
            get {
                return ResourceManager.GetString("MonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last year monthly average: .
        /// </summary>
        public static string MonthlyAverageLabel {
            get {
                return ResourceManager.GetString("MonthlyAverageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Budget:.
        /// </summary>
        public static string MonthlyBudgetLabel {
            get {
                return ResourceManager.GetString("MonthlyBudgetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the monthly cashflow for the selected account..
        /// </summary>
        public static string MonthlyCashflowDescription {
            get {
                return ResourceManager.GetString("MonthlyCashflowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Cashflow.
        /// </summary>
        public static string MonthlyCashflowLabel {
            get {
                return ResourceManager.GetString("MonthlyCashflowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Cashflow.
        /// </summary>
        public static string MonthlyCashflowTitle {
            get {
                return ResourceManager.GetString("MonthlyCashflowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string MonthlyLabel {
            get {
                return ResourceManager.GetString("MonthlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Spending Limit.
        /// </summary>
        public static string MonthlySpendingLimitLabel {
            get {
                return ResourceManager.GetString("MonthlySpendingLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string MoreTitle {
            get {
                return ResourceManager.GetString("MoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a name..
        /// </summary>
        public static string NameRequiredMessage {
            get {
                return ResourceManager.GetString("NameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextLabel {
            get {
                return ResourceManager.GetString("NextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Accounts to display..
        /// </summary>
        public static string NoAccountsMessage {
            get {
                return ResourceManager.GetString("NoAccountsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Budgets yet. Go ahead and create one!.
        /// </summary>
        public static string NoBudgetsMessage {
            get {
                return ResourceManager.GetString("NoBudgetsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no categories to display. .
        /// </summary>
        public static string NoCategoriesMessage {
            get {
                return ResourceManager.GetString("NoCategoriesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No Category].
        /// </summary>
        public static string NoCategoryLabel {
            get {
                return ResourceManager.GetString("NoCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entry selected. Choose a entry in the list to see the payments for it..
        /// </summary>
        public static string NoCategorySummaryEntrySelectedMessage {
            get {
                return ResourceManager.GetString("NoCategorySummaryEntrySelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Category.
        /// </summary>
        public static string NoCategoryTitle {
            get {
                return ResourceManager.GetString("NoCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to the internet. Please check your connection and try again..
        /// </summary>
        public static string NoNetworkMessage {
            get {
                return ResourceManager.GetString("NoNetworkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection.
        /// </summary>
        public static string NoNetworkTitle {
            get {
                return ResourceManager.GetString("NoNetworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Payments. Add one by tapping on the plus button..
        /// </summary>
        public static string NoPaymentsMessage {
            get {
                return ResourceManager.GetString("NoPaymentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string NoteLabel {
            get {
                return ResourceManager.GetString("NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter note to this payment...
        /// </summary>
        public static string NotePlaceholderLabel {
            get {
                return ResourceManager.GetString("NotePlaceholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Now.
        /// </summary>
        public static string NotNowLabel {
            get {
                return ResourceManager.GetString("NotNowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkLabel {
            get {
                return ResourceManager.GetString("OkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log.
        /// </summary>
        public static string OpenLogLabel {
            get {
                return ResourceManager.GetString("OpenLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string OthersLabel {
            get {
                return ResourceManager.GetString("OthersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing backups will be overwritten. Do you wanna continue?.
        /// </summary>
        public static string OverwriteBackupMessage {
            get {
                return ResourceManager.GetString("OverwriteBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your local data will be deleted. Are you sure you wanna proceed?.
        /// </summary>
        public static string OverwriteDataMessage {
            get {
                return ResourceManager.GetString("OverwriteDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite?.
        /// </summary>
        public static string OverwriteTitle {
            get {
                return ResourceManager.GetString("OverwriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you create a payment you can select the category for that payment along with the account and if it is an expense, an income or a transfer.
        ///Payments you created will show up under the account you choose.
        ///To get there go to the account list and select the respective account..
        /// </summary>
        public static string PaymentIntroductionText {
            get {
                return ResourceManager.GetString("PaymentIntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details for {0}.
        /// </summary>
        public static string PaymentsForCategoryTitle {
            get {
                return ResourceManager.GetString("PaymentsForCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type.
        /// </summary>
        public static string PaymentTypeLabel {
            get {
                return ResourceManager.GetString("PaymentTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string PersonalizationTitle {
            get {
                return ResourceManager.GetString("PersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly.
        /// </summary>
        public static string QuarterlyLabel {
            get {
                return ResourceManager.GetString("QuarterlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app!.
        /// </summary>
        public static string RateLabel {
            get {
                return ResourceManager.GetString("RateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you like our app. Support us with a rating in the store.
        ///Do you want to go the the store to rate?.
        /// </summary>
        public static string RateReminderText {
            get {
                return ResourceManager.GetString("RateReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        public static string RateReminderTitle {
            get {
                return ResourceManager.GetString("RateReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence.
        /// </summary>
        public static string RecurrenceLabel {
            get {
                return ResourceManager.GetString("RecurrenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Recurring.
        /// </summary>
        public static string RecurringLabel {
            get {
                return ResourceManager.GetString("RecurringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} payments assigned to this category.The assignment for those will be removed. Do you want to proceed?.
        /// </summary>
        public static string RemoveCategoryAssignmentOnPaymentMessage {
            get {
                return ResourceManager.GetString("RemoveCategoryAssignmentOnPaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Category Assignment.
        /// </summary>
        public static string RemoveCategoryAssignmentTitle {
            get {
                return ResourceManager.GetString("RemoveCategoryAssignmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveLabel {
            get {
                return ResourceManager.GetString("RemoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note required.
        /// </summary>
        public static string RequireNoteCheckbox {
            get {
                return ResourceManager.GetString("RequireNoteCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring backup was canceled..
        /// </summary>
        public static string RestoreBackupCanceledMessage {
            get {
                return ResourceManager.GetString("RestoreBackupCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the previous uploaded database backup and replace your local data with it.
        ///WARNING: Local changes you made meanwhile will be lost!.
        /// </summary>
        public static string RestoreBackupInformationLabel {
            get {
                return ResourceManager.GetString("RestoreBackupInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Backup.
        /// </summary>
        public static string RestoreBackupLabel {
            get {
                return ResourceManager.GetString("RestoreBackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string RevenueLabel {
            get {
                return ResourceManager.GetString("RevenueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo: {0}.
        /// </summary>
        public static string SaldoTemplate {
            get {
                return ResourceManager.GetString("SaldoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Account....
        /// </summary>
        public static string SavingAccountMessage {
            get {
                return ResourceManager.GetString("SavingAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Category....
        /// </summary>
        public static string SavingCategoryMessage {
            get {
                return ResourceManager.GetString("SavingCategoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Payment....
        /// </summary>
        public static string SavingPaymentMessage {
            get {
                return ResourceManager.GetString("SavingPaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category...
        /// </summary>
        public static string SelectCategoryLabel {
            get {
                return ResourceManager.GetString("SelectCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string SelectCategoryTitle {
            get {
                return ResourceManager.GetString("SelectCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string SelectDateLabel {
            get {
                return ResourceManager.GetString("SelectDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Account.
        /// </summary>
        public static string SelectedAccountHeader {
            get {
                return ResourceManager.GetString("SelectedAccountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Categories.
        /// </summary>
        public static string SelectedCategoriesLabel {
            get {
                return ResourceManager.GetString("SelectedCategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Payment Type.
        /// </summary>
        public static string SelectedPaymentTypeHeader {
            get {
                return ResourceManager.GetString("SelectedPaymentTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Filter.
        /// </summary>
        public static string SelectFilterTitle {
            get {
                return ResourceManager.GetString("SelectFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Statistic.
        /// </summary>
        public static string SelectStatisticTitle {
            get {
                return ResourceManager.GetString("SelectStatisticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the email application. Please try again later or contact us via &apos;mobile.support@apply-solutions.ch&apos;..
        /// </summary>
        public static string SendEmailFailedMessage {
            get {
                return ResourceManager.GetString("SendEmailFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your first account.
        /// </summary>
        public static string SetupAccountsSubtitle {
            get {
                return ResourceManager.GetString("SetupAccountsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use accounts to group together transactions. They can either mirror your bank account or be a virtual account just in the app..
        /// </summary>
        public static string SetupAccountsText {
            get {
                return ResourceManager.GetString("SetupAccountsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string SetupAccountsTitle {
            get {
                return ResourceManager.GetString("SetupAccountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string SkipLabel {
            get {
                return ResourceManager.GetString("SkipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Range:.
        /// </summary>
        public static string StatisticsTimeRangeTitle {
            get {
                return ResourceManager.GetString("StatisticsTimeRangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsTitle {
            get {
                return ResourceManager.GetString("StatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your Statistics.
        /// </summary>
        public static string StatisticsToolTip {
            get {
                return ResourceManager.GetString("StatisticsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Account.
        /// </summary>
        public static string TargetAccountLabel {
            get {
                return ResourceManager.GetString("TargetAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Range End.
        /// </summary>
        public static string TimeRangeEndLabel {
            get {
                return ResourceManager.GetString("TimeRangeEndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Range.
        /// </summary>
        public static string TimeRangeLabel {
            get {
                return ResourceManager.GetString("TimeRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Range Start.
        /// </summary>
        public static string TimeRangeStartLabel {
            get {
                return ResourceManager.GetString("TimeRangeStartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add transfer.
        /// </summary>
        public static string TransferHeader {
            get {
                return ResourceManager.GetString("TransferHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string TransferLabel {
            get {
                return ResourceManager.GetString("TransferLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is something not properly translated or not translated at all? Help us! Head over to crowdin and help improve the MoneyFox:.
        /// </summary>
        public static string TranslationLabel {
            get {
                return ResourceManager.GetString("TranslationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} payments assigned. Those will be unassigned. Do you want to proceed?.
        /// </summary>
        public static string UnassignPaymentMessage {
            get {
                return ResourceManager.GetString("UnassignPaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassign Payments.
        /// </summary>
        public static string UnassignPaymentTitle {
            get {
                return ResourceManager.GetString("UnassignPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unknown error. If the error persists, please restart the app..
        /// </summary>
        public static string UnknownErrorMessage {
            get {
                return ResourceManager.GetString("UnknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue during the operation..
        /// </summary>
        public static string UnknownErrorWithTextMessage {
            get {
                return ResourceManager.GetString("UnknownErrorWithTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload backup was canceled..
        /// </summary>
        public static string UploadBackupCanceledMessage {
            get {
                return ResourceManager.GetString("UploadBackupCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string WebsiteLabel {
            get {
                return ResourceManager.GetString("WebsiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string WeeklyLabel {
            get {
                return ResourceManager.GetString("WeeklyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string WelcomeLabel {
            get {
                return ResourceManager.GetString("WelcomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glad to have you!.
        /// </summary>
        public static string WelcomePageSubtitle {
            get {
                return ResourceManager.GetString("WelcomePageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MoneyFox helps you to track your expenses and incomes in an easy way.
        ///We will lead you through the first steps and help you get started..
        /// </summary>
        public static string WelcomePageText {
            get {
                return ResourceManager.GetString("WelcomePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Default.
        /// </summary>
        public static string WindowsDefaultLabel {
            get {
                return ResourceManager.GetString("WindowsDefaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string YearlyLabel {
            get {
                return ResourceManager.GetString("YearlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year to date.
        /// </summary>
        public static string YearToDateLabel {
            get {
                return ResourceManager.GetString("YearToDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
    }
}
