//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManager.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyManager.Localization.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select an account. ähnelt.
        /// </summary>
        public static string AccountRequiredMessage {
            get {
                return ResourceManager.GetString("AccountRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accounts ähnelt.
        /// </summary>
        public static string AccountsLabel {
            get {
                return ResourceManager.GetString("AccountsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Account ähnelt.
        /// </summary>
        public static string AddAccountTitle {
            get {
                return ResourceManager.GetString("AddAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Category  ähnelt.
        /// </summary>
        public static string AddCategoryTitle {
            get {
                return ResourceManager.GetString("AddCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Income ähnelt.
        /// </summary>
        public static string AddIncomeLabel {
            get {
                return ResourceManager.GetString("AddIncomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Income ähnelt.
        /// </summary>
        public static string AddIncomeTitle {
            get {
                return ResourceManager.GetString("AddIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Expense ähnelt.
        /// </summary>
        public static string AddSpendingLabel {
            get {
                return ResourceManager.GetString("AddSpendingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Expense ähnelt.
        /// </summary>
        public static string AddSpendingTitle {
            get {
                return ResourceManager.GetString("AddSpendingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Transfer ähnelt.
        /// </summary>
        public static string AddTransferLabel {
            get {
                return ResourceManager.GetString("AddTransferLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Transfer ähnelt.
        /// </summary>
        public static string AddTransferTitle {
            get {
                return ResourceManager.GetString("AddTransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Money Fox ähnelt.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup failed! ähnelt.
        /// </summary>
        public static string BackupFailedMessage {
            get {
                return ResourceManager.GetString("BackupFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup ähnelt.
        /// </summary>
        public static string BackupLabel {
            get {
                return ResourceManager.GetString("BackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Biweekly ähnelt.
        /// </summary>
        public static string BiweeklyLabel {
            get {
                return ResourceManager.GetString("BiweeklyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cashflow ähnelt.
        /// </summary>
        public static string CashflowLabel {
            get {
                return ResourceManager.GetString("CashflowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category Summary ähnelt.
        /// </summary>
        public static string CategorySummary {
            get {
                return ResourceManager.GetString("CategorySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This payment is recurring. Do you want to update the future payments aswell or just this occurence? ähnelt.
        /// </summary>
        public static string ChangeSubsequentPaymentMessage {
            get {
                return ResourceManager.GetString("ChangeSubsequentPaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Recurrence? ähnelt.
        /// </summary>
        public static string ChangeSubsequentPaymentTitle {
            get {
                return ResourceManager.GetString("ChangeSubsequentPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charged Account ähnelt.
        /// </summary>
        public static string ChargedAccountLabel {
            get {
                return ResourceManager.GetString("ChargedAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daily ähnelt.
        /// </summary>
        public static string DailyLabel {
            get {
                return ResourceManager.GetString("DailyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daily without weekend ähnelt.
        /// </summary>
        public static string DailyWithoutWeekendLabel {
            get {
                return ResourceManager.GetString("DailyWithoutWeekendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete this account? ähnelt.
        /// </summary>
        public static string DeleteAccountConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete this category? ähnelt.
        /// </summary>
        public static string DeleteCategoryConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteCategoryConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete this payment? ähnelt.
        /// </summary>
        public static string DeletePaymentConfirmationMessage {
            get {
                return ResourceManager.GetString("DeletePaymentConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete? ähnelt.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Category ähnelt.
        /// </summary>
        public static string EditCategoryTitle {
            get {
                return ResourceManager.GetString("EditCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Income ähnelt.
        /// </summary>
        public static string EditIncomeTitle {
            get {
                return ResourceManager.GetString("EditIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Expense ähnelt.
        /// </summary>
        public static string EditSpendingTitle {
            get {
                return ResourceManager.GetString("EditSpendingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Transfer ähnelt.
        /// </summary>
        public static string EditTransferTitle {
            get {
                return ResourceManager.GetString("EditTransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expenses ähnelt.
        /// </summary>
        public static string ExpenseLabel {
            get {
                return ResourceManager.GetString("ExpenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feedback ähnelt.
        /// </summary>
        public static string FeedbackLabel {
            get {
                return ResourceManager.GetString("FeedbackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feedback Money Fox ähnelt.
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gains ähnelt.
        /// </summary>
        public static string IncreaseLabel {
            get {
                return ResourceManager.GetString("IncreaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The enddate of a recurring payment has to be in the future. Please check your input. ähnelt.
        /// </summary>
        public static string InvalidEnddateMessage {
            get {
                return ResourceManager.GetString("InvalidEnddateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid End Date ähnelt.
        /// </summary>
        public static string InvalidEnddateTitle {
            get {
                return ResourceManager.GetString("InvalidEnddateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Just This ähnelt.
        /// </summary>
        public static string JustThisLabel {
            get {
                return ResourceManager.GetString("JustThisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We couldn&apos;t log you in. Please ensure you have an active internet connection. ähnelt.
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login failed! ähnelt.
        /// </summary>
        public static string LoginFailedTitle {
            get {
                return ResourceManager.GetString("LoginFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mandatory field ähnelt.
        /// </summary>
        public static string MandatoryFieldEmptyTitle {
            get {
                return ResourceManager.GetString("MandatoryFieldEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Menu ähnelt.
        /// </summary>
        public static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monthly ähnelt.
        /// </summary>
        public static string MonthlyLabel {
            get {
                return ResourceManager.GetString("MonthlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please insert a name. ähnelt.
        /// </summary>
        public static string NameRequiredMessage {
            get {
                return ResourceManager.GetString("NameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [No Name] ähnelt.
        /// </summary>
        public static string NoNamePlaceholderLabel {
            get {
                return ResourceManager.GetString("NoNamePlaceholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string NoneLabel {
            get {
                return ResourceManager.GetString("NoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Now ähnelt.
        /// </summary>
        public static string NotNowLabel {
            get {
                return ResourceManager.GetString("NotNowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        public static string OkLabel {
            get {
                return ResourceManager.GetString("OkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Existing backups will be overwritten. Do you wanna continue? ähnelt.
        /// </summary>
        public static string OverwriteBackupMessage {
            get {
                return ResourceManager.GetString("OverwriteBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your local data will be deleted. Are you sure you wanna proceed? ähnelt.
        /// </summary>
        public static string OverwriteDataMessage {
            get {
                return ResourceManager.GetString("OverwriteDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite? ähnelt.
        /// </summary>
        public static string OverwriteTitle {
            get {
                return ResourceManager.GetString("OverwriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The passwod and the password confirmation didn&apos;t match. Please check your input. ähnelt.
        /// </summary>
        public static string PasswordConfirmationWrongMessage {
            get {
                return ResourceManager.GetString("PasswordConfirmationWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password confirmation ähnelt.
        /// </summary>
        public static string PasswordConfirmationWrongTitle {
            get {
                return ResourceManager.GetString("PasswordConfirmationWrongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password was saved succesfully. ähnelt.
        /// </summary>
        public static string PasswordSavedMessage {
            get {
                return ResourceManager.GetString("PasswordSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password saved ähnelt.
        /// </summary>
        public static string PasswordSavedTitle {
            get {
                return ResourceManager.GetString("PasswordSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password you entered was not correct. Please try again. ähnelt.
        /// </summary>
        public static string PasswordWrongMessage {
            get {
                return ResourceManager.GetString("PasswordWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password wrong ähnelt.
        /// </summary>
        public static string PasswordWrongTitle {
            get {
                return ResourceManager.GetString("PasswordWrongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We hope you like our app. Support us with a rating in the store.
        ///Do you want to go the the store to rate? ähnelt.
        /// </summary>
        public static string RateReminderText {
            get {
                return ResourceManager.GetString("RateReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rate this app ähnelt.
        /// </summary>
        public static string RateReminderTitle {
            get {
                return ResourceManager.GetString("RateReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update All ähnelt.
        /// </summary>
        public static string RecurringLabel {
            get {
                return ResourceManager.GetString("RecurringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore failed! ähnelt.
        /// </summary>
        public static string RestoreFailedMessage {
            get {
                return ResourceManager.GetString("RestoreFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revenue ähnelt.
        /// </summary>
        public static string RevenueLabel {
            get {
                return ResourceManager.GetString("RevenueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Security ähnelt.
        /// </summary>
        public static string SecurityTitle {
            get {
                return ResourceManager.GetString("SecurityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Date ähnelt.
        /// </summary>
        public static string SelectDateTitle {
            get {
                return ResourceManager.GetString("SelectDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die select operation ähnelt.
        /// </summary>
        public static string SelectOperationLabel {
            get {
                return ResourceManager.GetString("SelectOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shortcuts ähnelt.
        /// </summary>
        public static string ShortcutsTitle {
            get {
                return ResourceManager.GetString("ShortcutsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category Spreading ähnelt.
        /// </summary>
        public static string SpreadingLabel {
            get {
                return ResourceManager.GetString("SpreadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistics ähnelt.
        /// </summary>
        public static string StatisticsLabel {
            get {
                return ResourceManager.GetString("StatisticsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistic ähnelt.
        /// </summary>
        public static string StatisticTitle {
            get {
                return ResourceManager.GetString("StatisticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success! ähnelt.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target Account ähnelt.
        /// </summary>
        public static string TargetAccountLabel {
            get {
                return ResourceManager.GetString("TargetAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task was successful completed. ähnelt.
        /// </summary>
        public static string TaskSuccessfulMessage {
            get {
                return ResourceManager.GetString("TaskSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weekly ähnelt.
        /// </summary>
        public static string WeeklyLabel {
            get {
                return ResourceManager.GetString("WeeklyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yearly ähnelt.
        /// </summary>
        public static string YearlyLabel {
            get {
                return ResourceManager.GetString("YearlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
    }
}
