//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManager.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_de() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyManager.Localization.Strings.de", typeof(Strings_de).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte Konto auswählen. ähnelt.
        /// </summary>
        internal static string AccountRequiredMessage {
            get {
                return ResourceManager.GetString("AccountRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konten ähnelt.
        /// </summary>
        internal static string AccountsLabel {
            get {
                return ResourceManager.GetString("AccountsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konto hinzufügen ähnelt.
        /// </summary>
        internal static string AddAccountTitle {
            get {
                return ResourceManager.GetString("AddAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorie hinzufügen  ähnelt.
        /// </summary>
        internal static string AddCategoryTitle {
            get {
                return ResourceManager.GetString("AddCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einnahme hinzufügen ähnelt.
        /// </summary>
        internal static string AddIncomeLabel {
            get {
                return ResourceManager.GetString("AddIncomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einnahme hinzufügen ähnelt.
        /// </summary>
        internal static string AddIncomeTitle {
            get {
                return ResourceManager.GetString("AddIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgabe hinzufügen ähnelt.
        /// </summary>
        internal static string AddSpendingLabel {
            get {
                return ResourceManager.GetString("AddSpendingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgabe hinzufügen ähnelt.
        /// </summary>
        internal static string AddSpendingTitle {
            get {
                return ResourceManager.GetString("AddSpendingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        internal static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übertrag hinzufügen ähnelt.
        /// </summary>
        internal static string AddTransferLabel {
            get {
                return ResourceManager.GetString("AddTransferLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übertrag hinzufügen ähnelt.
        /// </summary>
        internal static string AddTransferTitle {
            get {
                return ResourceManager.GetString("AddTransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Money Fox ähnelt.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sicherung fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string BackupFailedMessage {
            get {
                return ResourceManager.GetString("BackupFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sicherung ähnelt.
        /// </summary>
        internal static string BackupLabel {
            get {
                return ResourceManager.GetString("BackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zweiwöchentlich ähnelt.
        /// </summary>
        internal static string BiweeklyLabel {
            get {
                return ResourceManager.GetString("BiweeklyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kapitalfluss ähnelt.
        /// </summary>
        internal static string CashflowLabel {
            get {
                return ResourceManager.GetString("CashflowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorie Zusammenfassung ähnelt.
        /// </summary>
        internal static string CategorySummary {
            get {
                return ResourceManager.GetString("CategorySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dies ist eine wiederkehrende Zahlung. Soll die Anpassung auch auf künftige Zahlungen übernommen werden oder nur auf diese? ähnelt.
        /// </summary>
        internal static string ChangeSubsequentPaymentMessage {
            get {
                return ResourceManager.GetString("ChangeSubsequentPaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wiederholungen aktualisieren? ähnelt.
        /// </summary>
        internal static string ChangeSubsequentPaymentTitle {
            get {
                return ResourceManager.GetString("ChangeSubsequentPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Belastungskonto ähnelt.
        /// </summary>
        internal static string ChargedAccountLabel {
            get {
                return ResourceManager.GetString("ChargedAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Täglich ähnelt.
        /// </summary>
        internal static string DailyLabel {
            get {
                return ResourceManager.GetString("DailyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Täglich ohne Wochenende ähnelt.
        /// </summary>
        internal static string DailyWithoutWeekendLabel {
            get {
                return ResourceManager.GetString("DailyWithoutWeekendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du dieses Konto wirklich löschen? ähnelt.
        /// </summary>
        internal static string DeleteAccountConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du diese Kategorie wirklich löschen? ähnelt.
        /// </summary>
        internal static string DeleteCategoryConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteCategoryConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        internal static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du diese Zahlung wirklich löschen? ähnelt.
        /// </summary>
        internal static string DeletePaymentConfirmationMessage {
            get {
                return ResourceManager.GetString("DeletePaymentConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen? ähnelt.
        /// </summary>
        internal static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorie bearbeiten ähnelt.
        /// </summary>
        internal static string EditCategoryTitle {
            get {
                return ResourceManager.GetString("EditCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einnahme bearbeiten ähnelt.
        /// </summary>
        internal static string EditIncomeTitle {
            get {
                return ResourceManager.GetString("EditIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        internal static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgabe bearbeiten ähnelt.
        /// </summary>
        internal static string EditSpendingTitle {
            get {
                return ResourceManager.GetString("EditSpendingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        internal static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übertrag bearbeiten ähnelt.
        /// </summary>
        internal static string EditTransferTitle {
            get {
                return ResourceManager.GetString("EditTransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgabe ähnelt.
        /// </summary>
        internal static string ExpenseLabel {
            get {
                return ResourceManager.GetString("ExpenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rückmeldung ähnelt.
        /// </summary>
        internal static string FeedbackLabel {
            get {
                return ResourceManager.GetString("FeedbackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rückmeldungen Money Fox ähnelt.
        /// </summary>
        internal static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gewinn ähnelt.
        /// </summary>
        internal static string IncreaseLabel {
            get {
                return ResourceManager.GetString("IncreaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Enddatum der Wiederkehrenden Transaktion muss in der Zukunft liegen. Bitte überprüfe deine Eingabe. ähnelt.
        /// </summary>
        internal static string InvalidEnddateMessage {
            get {
                return ResourceManager.GetString("InvalidEnddateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültiges Enddatum ähnelt.
        /// </summary>
        internal static string InvalidEnddateTitle {
            get {
                return ResourceManager.GetString("InvalidEnddateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nur diese ähnelt.
        /// </summary>
        internal static string JustThisLabel {
            get {
                return ResourceManager.GetString("JustThisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wir konnten dich nicht einloggen. Bitte prüfe ob du mit dem Internet verbunden bist. ähnelt.
        /// </summary>
        internal static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string LoginFailedTitle {
            get {
                return ResourceManager.GetString("LoginFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pflichtfeld ähnelt.
        /// </summary>
        internal static string MandatoryFieldEmptyTitle {
            get {
                return ResourceManager.GetString("MandatoryFieldEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Menu ähnelt.
        /// </summary>
        internal static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monatlich ähnelt.
        /// </summary>
        internal static string MonthlyLabel {
            get {
                return ResourceManager.GetString("MonthlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte gib einen Namen ein. ähnelt.
        /// </summary>
        internal static string NameRequiredMessage {
            get {
                return ResourceManager.GetString("NameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        internal static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [Kein Name] ähnelt.
        /// </summary>
        internal static string NoNamePlaceholderLabel {
            get {
                return ResourceManager.GetString("NoNamePlaceholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine ähnelt.
        /// </summary>
        internal static string NoneLabel {
            get {
                return ResourceManager.GetString("NoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht jetzt ähnelt.
        /// </summary>
        internal static string NotNowLabel {
            get {
                return ResourceManager.GetString("NotNowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OkLabel {
            get {
                return ResourceManager.GetString("OkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Existierende Sicherungen werden überschrieben. Möchtest du Fortfahren? ähnelt.
        /// </summary>
        internal static string OverwriteBackupMessage {
            get {
                return ResourceManager.GetString("OverwriteBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Lokalen Daten werden überschrieben. Möchtest du fortfahren? ähnelt.
        /// </summary>
        internal static string OverwriteDataMessage {
            get {
                return ResourceManager.GetString("OverwriteDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überschreiben? ähnelt.
        /// </summary>
        internal static string OverwriteTitle {
            get {
                return ResourceManager.GetString("OverwriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Passwort und die Passwortbestätigung waren nicht übereinstimmend. Bitte überprüfe deine Eingabe. ähnelt.
        /// </summary>
        internal static string PasswordConfirmationWrongMessage {
            get {
                return ResourceManager.GetString("PasswordConfirmationWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwortbestätigung ähnelt.
        /// </summary>
        internal static string PasswordConfirmationWrongTitle {
            get {
                return ResourceManager.GetString("PasswordConfirmationWrongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort wurde erfolgreich gespeichert. ähnelt.
        /// </summary>
        internal static string PasswordSavedMessage {
            get {
                return ResourceManager.GetString("PasswordSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort gespeichert ähnelt.
        /// </summary>
        internal static string PasswordSavedTitle {
            get {
                return ResourceManager.GetString("PasswordSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das eingegebene Passwort war falsch. Bitte prüfe deine Eingabe nochmals. ähnelt.
        /// </summary>
        internal static string PasswordWrongMessage {
            get {
                return ResourceManager.GetString("PasswordWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort falsch ähnelt.
        /// </summary>
        internal static string PasswordWrongTitle {
            get {
                return ResourceManager.GetString("PasswordWrongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wir hoffen dass dir unser App gefällt. Unterstütze uns mit einer Bewertung.
        ///Möchtest du jetzt in den store gehen um eine Bewertung abzugeben? ähnelt.
        /// </summary>
        internal static string RateReminderText {
            get {
                return ResourceManager.GetString("RateReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bewerte dieses App ähnelt.
        /// </summary>
        internal static string RateReminderTitle {
            get {
                return ResourceManager.GetString("RateReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle aktualisieren ähnelt.
        /// </summary>
        internal static string RecurringLabel {
            get {
                return ResourceManager.GetString("RecurringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wiederherstellen fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string RestoreFailedMessage {
            get {
                return ResourceManager.GetString("RestoreFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einkommen ähnelt.
        /// </summary>
        internal static string RevenueLabel {
            get {
                return ResourceManager.GetString("RevenueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum wählen ähnelt.
        /// </summary>
        internal static string SelectDateTitle {
            get {
                return ResourceManager.GetString("SelectDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operation auswählen ähnelt.
        /// </summary>
        internal static string SelectOperationLabel {
            get {
                return ResourceManager.GetString("SelectOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorienverteilung ähnelt.
        /// </summary>
        internal static string SpreadingLabel {
            get {
                return ResourceManager.GetString("SpreadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistik ähnelt.
        /// </summary>
        internal static string StatisticsLabel {
            get {
                return ResourceManager.GetString("StatisticsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistik ähnelt.
        /// </summary>
        internal static string StatisticTitle {
            get {
                return ResourceManager.GetString("StatisticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erfolg! ähnelt.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gutschriftkonto ähnelt.
        /// </summary>
        internal static string TargetAccountLabel {
            get {
                return ResourceManager.GetString("TargetAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aufgabe wurde Erfolgreich abgeschlossen. ähnelt.
        /// </summary>
        internal static string TaskSuccessfulMessage {
            get {
                return ResourceManager.GetString("TaskSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wochentlich ähnelt.
        /// </summary>
        internal static string WeeklyLabel {
            get {
                return ResourceManager.GetString("WeeklyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jährlich ähnelt.
        /// </summary>
        internal static string YearlyLabel {
            get {
                return ResourceManager.GetString("YearlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        internal static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
    }
}
