using System;
using PropertyChanged;
using SQLite.Net.Attributes;
using SQLiteNetExtensions.Attributes;

namespace MoneyManager.Foundation.Model
{
    /// <summary>
    ///     Databasemodel for payments. Includes expenses, income and transfers.
    ///     Databasetable: Payments
    /// </summary>
    [ImplementPropertyChanged]
    [Table("Payments")]
    public class Payment
    {
        /// <summary>
        ///     Primary Key. Is generated by the database on insert.
        /// </summary>
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }

        /// <summary>
        ///     In case it's a expense or transfer the foreign key to the <see cref="Account" /> who will be charged.
        ///     In case it's an income the  foreign key to the <see cref="Account" /> who will be credited.
        /// </summary>
        [ForeignKey(typeof (Account))]
        public int ChargedAccountId { get; set; }

        /// <summary>
        ///     Foreign key to the account who will be credited by a transfer.
        ///     Not used for the other payment types.
        /// </summary>
        [ForeignKey(typeof (Account))]
        public int TargetAccountId { get; set; }

        /// <summary>
        ///     Foreign key to the <see cref="Category" /> for this payment
        /// </summary>
        [ForeignKey(typeof (Category))]
        public int? CategoryId { get; set; }

        /// <summary>
        ///     Date when this payment will be executed.
        /// </summary>
        public DateTime Date { get; set; }

        /// <summary>
        ///     Amount of the payment. Has to be >= 0. If the amount is charged or not is based on the payment type.
        /// </summary>
        public double Amount { get; set; }

        /// <summary>
        ///     Indicates if this payment was already executed and the amount already credited or charged to the respective
        ///     account.
        /// </summary>
        public bool IsCleared { get; set; }

        /// <summary>
        ///     Type of the payment. This is the int of the Enum <see cref="PaymentType" />.
        /// </summary>
        public int Type { get; set; }

        /// <summary>
        ///     Additional notes to the payment.
        /// </summary>
        public string Note { get; set; }

        /// <summary>
        ///     Indicates if the payment will be repeated or if it's a uniquie payment.
        /// </summary>
        public bool IsRecurring { get; set; }

        /// <summary>
        ///     Foreign key to the <see cref="RecurringPayment" /> if it's recurring.
        /// </summary>
        [ForeignKey(typeof (RecurringPayment))]
        public int RecurringPaymentId { get; set; }

        /// <summary>
        ///     In case it's a expense or transfer the account who will be charged.
        ///     In case it's an income the account who will be credited.
        /// </summary>
        [ManyToOne("ChargedAccountId", CascadeOperations = CascadeOperation.All)]
        public Account ChargedAccount { get; set; }

        /// <summary>
        ///     The <see cref="Account" /> who will be credited by a transfer.
        ///     Not used for the other payment types.
        /// </summary>
        [ManyToOne("TargetAccountId", CascadeOperations = CascadeOperation.All)]
        public Account TargetAccount { get; set; }

        /// <summary>
        ///     The <see cref="Category" /> for this payment
        /// </summary>
        [ManyToOne]
        public Category Category { get; set; }

        /// <summary>
        ///     The <see cref="RecurringPayment" /> if it's recurring.
        /// </summary>
        [ManyToOne("RecurringPaymentId", CascadeOperations = CascadeOperation.All)]
        public RecurringPayment RecurringPayment { get; set; }

        /// <summary>
        ///     Checks if the payment is ready to clear based on the date of
        ///     the payment and the current date.
        /// </summary>
        [Ignore]
        public bool ClearPaymentNow => Date.Date <= DateTime.Now.Date;

        /// <summary>
        ///     This is a shortcut to access if the payment is a transfer or not.
        /// </summary>
        [Ignore]
        public bool IsTransfer => Type == (int) PaymentType.Transfer;
    }
}