#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MoneyManager.Droid.Resource", IsApplication=true)]

namespace MoneyManager.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::MoneyManager.Droid.Resource.Attribute.MvxBind;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::MoneyManager.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::MoneyManager.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::MoneyManager.Droid.Resource.Attribute.MvxItemTemplate;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::MoneyManager.Droid.Resource.Attribute.MvxLang;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::MoneyManager.Droid.Resource.Attribute.MvxSource;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::MoneyManager.Droid.Resource.Attribute.MvxTemplate;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::MoneyManager.Droid.Resource.Id.MvvmCrossTagId;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::MoneyManager.Droid.Resource.Id.MvxBindingTagUnique;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::MoneyManager.Droid.Resource.Styleable.MvxBinding;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::MoneyManager.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::MoneyManager.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::MoneyManager.Droid.Resource.Styleable.MvxControl;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::MoneyManager.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::MoneyManager.Droid.Resource.Styleable.MvxExpandableListView;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::MoneyManager.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::MoneyManager.Droid.Resource.Styleable.MvxImageView;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::MoneyManager.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::MoneyManager.Droid.Resource.Styleable.MvxListView;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::MoneyManager.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::Cirrious.MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::MoneyManager.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Attribute.MvxBind = global::MoneyManager.Droid.Resource.Attribute.MvxBind;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::MoneyManager.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Attribute.MvxGroupItemTemplate = global::MoneyManager.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Attribute.MvxItemTemplate = global::MoneyManager.Droid.Resource.Attribute.MvxItemTemplate;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Attribute.MvxLang = global::MoneyManager.Droid.Resource.Attribute.MvxLang;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Attribute.MvxSource = global::MoneyManager.Droid.Resource.Attribute.MvxSource;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Attribute.MvxTemplate = global::MoneyManager.Droid.Resource.Attribute.MvxTemplate;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_disclosure = global::MoneyManager.Droid.Resource.Drawable.dialog_disclosure;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_expander_ic_minimized = global::MoneyManager.Droid.Resource.Drawable.dialog_expander_ic_minimized;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_icon = global::MoneyManager.Droid.Resource.Drawable.dialog_icon;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_spinner_default_holo_dark = global::MoneyManager.Droid.Resource.Drawable.dialog_spinner_default_holo_dark;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_spinner_default_holo_light = global::MoneyManager.Droid.Resource.Drawable.dialog_spinner_default_holo_light;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.MvvmCrossTagId = global::MoneyManager.Droid.Resource.Id.MvvmCrossTagId;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.MvxBindingTagUnique = global::MoneyManager.Droid.Resource.Id.MvxBindingTagUnique;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_BoolField = global::MoneyManager.Droid.Resource.Id.dialog_BoolField;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_Button = global::MoneyManager.Droid.Resource.Id.dialog_Button;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_DisclosureField = global::MoneyManager.Droid.Resource.Id.dialog_DisclosureField;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_HtmlField = global::MoneyManager.Droid.Resource.Id.dialog_HtmlField;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_ImageLeft = global::MoneyManager.Droid.Resource.Id.dialog_ImageLeft;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_ImageRight = global::MoneyManager.Droid.Resource.Id.dialog_ImageRight;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelField = global::MoneyManager.Droid.Resource.Id.dialog_LabelField;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelPercentageField = global::MoneyManager.Droid.Resource.Id.dialog_LabelPercentageField;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelSubtextField = global::MoneyManager.Droid.Resource.Id.dialog_LabelSubtextField;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_Panel = global::MoneyManager.Droid.Resource.Id.dialog_Panel;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_RadioButtonList = global::MoneyManager.Droid.Resource.Id.dialog_RadioButtonList;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_SliderField = global::MoneyManager.Droid.Resource.Id.dialog_SliderField;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_Spinner = global::MoneyManager.Droid.Resource.Id.dialog_Spinner;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_ValueField = global::MoneyManager.Droid.Resource.Id.dialog_ValueField;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Id.iFormFieldValue = global::MoneyManager.Droid.Resource.Id.iFormFieldValue;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_achievements = global::MoneyManager.Droid.Resource.Layout.dialog_achievements;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldleft = global::MoneyManager.Droid.Resource.Layout.dialog_boolfieldleft;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldright = global::MoneyManager.Droid.Resource.Layout.dialog_boolfieldright;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldsubleft = global::MoneyManager.Droid.Resource.Layout.dialog_boolfieldsubleft;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldsubright = global::MoneyManager.Droid.Resource.Layout.dialog_boolfieldsubright;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_button = global::MoneyManager.Droid.Resource.Layout.dialog_button;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_datefield = global::MoneyManager.Droid.Resource.Layout.dialog_datefield;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_fieldsetlabel = global::MoneyManager.Droid.Resource.Layout.dialog_fieldsetlabel;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_floatimage = global::MoneyManager.Droid.Resource.Layout.dialog_floatimage;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_html = global::MoneyManager.Droid.Resource.Layout.dialog_html;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_labeldisclosure = global::MoneyManager.Droid.Resource.Layout.dialog_labeldisclosure;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_labelfieldbelow = global::MoneyManager.Droid.Resource.Layout.dialog_labelfieldbelow;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_labelfieldright = global::MoneyManager.Droid.Resource.Layout.dialog_labelfieldright;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_multiline_labelfieldbelow = global::MoneyManager.Droid.Resource.Layout.dialog_multiline_labelfieldbelow;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_onofffieldright = global::MoneyManager.Droid.Resource.Layout.dialog_onofffieldright;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_panel = global::MoneyManager.Droid.Resource.Layout.dialog_panel;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_root = global::MoneyManager.Droid.Resource.Layout.dialog_root;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_selectlist = global::MoneyManager.Droid.Resource.Layout.dialog_selectlist;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_selectlistfield = global::MoneyManager.Droid.Resource.Layout.dialog_selectlistfield;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_textarea = global::MoneyManager.Droid.Resource.Layout.dialog_textarea;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_textfieldbelow = global::MoneyManager.Droid.Resource.Layout.dialog_textfieldbelow;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_textfieldright = global::MoneyManager.Droid.Resource.Layout.dialog_textfieldright;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Styleable.MvxBinding = global::MoneyManager.Droid.Resource.Styleable.MvxBinding;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Styleable.MvxBinding_MvxBind = global::MoneyManager.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Styleable.MvxBinding_MvxLang = global::MoneyManager.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Styleable.MvxControl = global::MoneyManager.Droid.Resource.Styleable.MvxControl;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::MoneyManager.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Styleable.MvxExpandableListView = global::MoneyManager.Droid.Resource.Styleable.MvxExpandableListView;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::MoneyManager.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Styleable.MvxImageView = global::MoneyManager.Droid.Resource.Styleable.MvxImageView;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Styleable.MvxImageView_MvxSource = global::MoneyManager.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Styleable.MvxListView = global::MoneyManager.Droid.Resource.Styleable.MvxListView;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::MoneyManager.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::Cirrious.MvvmCross.Dialog.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::MoneyManager.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Attribute.MvxBind = global::MoneyManager.Droid.Resource.Attribute.MvxBind;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Attribute.MvxDropDownItemTemplate = global::MoneyManager.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Attribute.MvxGroupItemTemplate = global::MoneyManager.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Attribute.MvxItemTemplate = global::MoneyManager.Droid.Resource.Attribute.MvxItemTemplate;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Attribute.MvxLang = global::MoneyManager.Droid.Resource.Attribute.MvxLang;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Attribute.MvxSource = global::MoneyManager.Droid.Resource.Attribute.MvxSource;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Attribute.MvxTemplate = global::MoneyManager.Droid.Resource.Attribute.MvxTemplate;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Id.MvvmCrossTagId = global::MoneyManager.Droid.Resource.Id.MvvmCrossTagId;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Id.MvxBindingTagUnique = global::MoneyManager.Droid.Resource.Id.MvxBindingTagUnique;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.String.ApplicationName = global::MoneyManager.Droid.Resource.String.ApplicationName;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.String.Hello = global::MoneyManager.Droid.Resource.String.Hello;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding = global::MoneyManager.Droid.Resource.Styleable.MvxBinding;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding_MvxBind = global::MoneyManager.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding_MvxLang = global::MoneyManager.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Styleable.MvxControl = global::MoneyManager.Droid.Resource.Styleable.MvxControl;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Styleable.MvxControl_MvxTemplate = global::MoneyManager.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Styleable.MvxExpandableListView = global::MoneyManager.Droid.Resource.Styleable.MvxExpandableListView;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::MoneyManager.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Styleable.MvxImageView = global::MoneyManager.Droid.Resource.Styleable.MvxImageView;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Styleable.MvxImageView_MvxSource = global::MoneyManager.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView = global::MoneyManager.Droid.Resource.Styleable.MvxListView;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::MoneyManager.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView_MvxItemTemplate = global::MoneyManager.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.ApplicationName = global::MoneyManager.Droid.Resource.String.ApplicationName;
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.Hello = global::MoneyManager.Droid.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::MoneyManager.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::MoneyManager.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dialog_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dialog_spinner_default_holo_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dialog_spinner_default_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_add_circle = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_delete = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_done = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_forward = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_remove_circle = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_save = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int logo = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050015
			public const int ChargedAccount = 2131034133;
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f050016
			public const int TargetAccount = 2131034134;
			
			// aapt resource value: 0x7f050002
			public const int accountList = 2131034114;
			
			// aapt resource value: 0x7f05001b
			public const int action_add_account = 2131034139;
			
			// aapt resource value: 0x7f050018
			public const int action_add_income = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int action_add_spending = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int action_add_transfer = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int action_delete = 2131034140;
			
			// aapt resource value: 0x7f050017
			public const int action_save = 2131034135;
			
			// aapt resource value: 0x7f050014
			public const int content_pane = 2131034132;
			
			// aapt resource value: 0x7f050007
			public const int dialog_BoolField = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int dialog_Button = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int dialog_DisclosureField = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int dialog_HtmlField = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int dialog_ImageLeft = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int dialog_ImageRight = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int dialog_LabelField = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int dialog_LabelPercentageField = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int dialog_LabelSubtextField = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int dialog_Panel = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int dialog_RadioButtonList = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int dialog_SliderField = 2131034123;
			
			// aapt resource value: 0x7f050010
			public const int dialog_Spinner = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int dialog_ValueField = 2131034121;
			
			// aapt resource value: 0x7f050011
			public const int iFormFieldValue = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int left_pane = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int main_layout = 2131034130;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AccountListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AccountListLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_achievements = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_boolfieldleft = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_boolfieldright = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_boolfieldsubleft = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_boolfieldsubright = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_button = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_datefield = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_fieldsetlabel = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_floatimage = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_html = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_labeldisclosure = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_labelfieldbelow = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_labelfieldright = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_multiline_labelfieldbelow = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_onofffieldright = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_panel = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int dialog_root = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int dialog_selectlist = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int dialog_selectlistfield = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int dialog_textarea = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int dialog_textfieldbelow = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int dialog_textfieldright = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int MainLayout = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int ModifyAccountLayout = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int ModifyTransactionLayout = 2130903067;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int AddMenu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MainMenu = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ModificationMenu = 2131099650;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int action_add_account = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int action_add_income = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int action_add_spending = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int action_add_transfer = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int action_delete = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int action_save = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040012
			public const int button_rate = 2130968594;
			
			// aapt resource value: 0x7f040009
			public const int hint_account_name = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int hint_amount = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int hint_current_balance = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int hint_iban = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int hint_note = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int textview_contact = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int textview_github = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int textview_opensource = 2130968593;
			
			// aapt resource value: 0x7f04000e
			public const int textview_version = 2130968590;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
