//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyFox.Foundation.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MoneyFox.Foundation.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        public static string AccountRequiredMessage {
            get {
                return ResourceManager.GetString("AccountRequiredMessage", resourceCulture);
            }
        }
        
        public static string AccountsLabel {
            get {
                return ResourceManager.GetString("AccountsLabel", resourceCulture);
            }
        }
        
        public static string AddAccountTitle {
            get {
                return ResourceManager.GetString("AddAccountTitle", resourceCulture);
            }
        }
        
        public static string AddIncomeLabel {
            get {
                return ResourceManager.GetString("AddIncomeLabel", resourceCulture);
            }
        }
        
        public static string AddExpenseLabel {
            get {
                return ResourceManager.GetString("AddExpenseLabel", resourceCulture);
            }
        }
        
        public static string AddTransferLabel {
            get {
                return ResourceManager.GetString("AddTransferLabel", resourceCulture);
            }
        }
        
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        public static string ErrorMessageBackupFailed {
            get {
                return ResourceManager.GetString("ErrorMessageBackupFailed", resourceCulture);
            }
        }
        
        public static string BackupLabel {
            get {
                return ResourceManager.GetString("BackupLabel", resourceCulture);
            }
        }
        
        public static string CashflowLabel {
            get {
                return ResourceManager.GetString("CashflowLabel", resourceCulture);
            }
        }
        
        public static string ChangeSubsequentPaymentMessage {
            get {
                return ResourceManager.GetString("ChangeSubsequentPaymentMessage", resourceCulture);
            }
        }
        
        public static string ChangeSubsequentPaymentTitle {
            get {
                return ResourceManager.GetString("ChangeSubsequentPaymentTitle", resourceCulture);
            }
        }
        
        public static string DailyLabel {
            get {
                return ResourceManager.GetString("DailyLabel", resourceCulture);
            }
        }
        
        public static string DailyWithoutWeekendLabel {
            get {
                return ResourceManager.GetString("DailyWithoutWeekendLabel", resourceCulture);
            }
        }
        
        public static string DeleteAccountConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmationMessage", resourceCulture);
            }
        }
        
        public static string DeleteCategoryConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteCategoryConfirmationMessage", resourceCulture);
            }
        }
        
        public static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        public static string SecurityTitle {
            get {
                return ResourceManager.GetString("SecurityTitle", resourceCulture);
            }
        }
        
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        public static string DeletePaymentConfirmationMessage {
            get {
                return ResourceManager.GetString("DeletePaymentConfirmationMessage", resourceCulture);
            }
        }
        
        public static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        public static string ExpenseLabel {
            get {
                return ResourceManager.GetString("ExpenseLabel", resourceCulture);
            }
        }
        
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        public static string EditIncomeTitle {
            get {
                return ResourceManager.GetString("EditIncomeTitle", resourceCulture);
            }
        }
        
        public static string IncreaseLabel {
            get {
                return ResourceManager.GetString("IncreaseLabel", resourceCulture);
            }
        }
        
        public static string JustThisLabel {
            get {
                return ResourceManager.GetString("JustThisLabel", resourceCulture);
            }
        }
        
        public static string MandatoryFieldEmptyTitle {
            get {
                return ResourceManager.GetString("MandatoryFieldEmptyTitle", resourceCulture);
            }
        }
        
        public static string MonthlyLabel {
            get {
                return ResourceManager.GetString("MonthlyLabel", resourceCulture);
            }
        }
        
        public static string NameRequiredMessage {
            get {
                return ResourceManager.GetString("NameRequiredMessage", resourceCulture);
            }
        }
        
        public static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        public static string OkLabel {
            get {
                return ResourceManager.GetString("OkLabel", resourceCulture);
            }
        }
        
        public static string OverwriteBackupMessage {
            get {
                return ResourceManager.GetString("OverwriteBackupMessage", resourceCulture);
            }
        }
        
        public static string OverwriteTitle {
            get {
                return ResourceManager.GetString("OverwriteTitle", resourceCulture);
            }
        }
        
        public static string UpdateAllLabel {
            get {
                return ResourceManager.GetString("UpdateAllLabel", resourceCulture);
            }
        }
        
        public static string RevenueLabel {
            get {
                return ResourceManager.GetString("RevenueLabel", resourceCulture);
            }
        }
        
        public static string SelectDateTitle {
            get {
                return ResourceManager.GetString("SelectDateTitle", resourceCulture);
            }
        }
        
        public static string SelectOperationLabel {
            get {
                return ResourceManager.GetString("SelectOperationLabel", resourceCulture);
            }
        }
        
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        public static string EditSpendingTitle {
            get {
                return ResourceManager.GetString("EditSpendingTitle", resourceCulture);
            }
        }
        
        public static string StatisticsLabel {
            get {
                return ResourceManager.GetString("StatisticsLabel", resourceCulture);
            }
        }
        
        public static string StatisticsTitle {
            get {
                return ResourceManager.GetString("StatisticsTitle", resourceCulture);
            }
        }
        
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        public static string TaskSuccessfulMessage {
            get {
                return ResourceManager.GetString("TaskSuccessfulMessage", resourceCulture);
            }
        }
        
        public static string EditTransferTitle {
            get {
                return ResourceManager.GetString("EditTransferTitle", resourceCulture);
            }
        }
        
        public static string WeeklyLabel {
            get {
                return ResourceManager.GetString("WeeklyLabel", resourceCulture);
            }
        }
        
        public static string YearlyLabel {
            get {
                return ResourceManager.GetString("YearlyLabel", resourceCulture);
            }
        }
        
        public static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
        
        public static string OverwriteDataMessage {
            get {
                return ResourceManager.GetString("OverwriteDataMessage", resourceCulture);
            }
        }
        
        public static string AddIncomeTitle {
            get {
                return ResourceManager.GetString("AddIncomeTitle", resourceCulture);
            }
        }
        
        public static string AddExpenseTitle {
            get {
                return ResourceManager.GetString("AddExpenseTitle", resourceCulture);
            }
        }
        
        public static string AddTransferTitle {
            get {
                return ResourceManager.GetString("AddTransferTitle", resourceCulture);
            }
        }
        
        public static string EditAccountTitle {
            get {
                return ResourceManager.GetString("EditAccountTitle", resourceCulture);
            }
        }
        
        public static string PasswordConfirmationWrongMessage {
            get {
                return ResourceManager.GetString("PasswordConfirmationWrongMessage", resourceCulture);
            }
        }
        
        public static string PasswordConfirmationWrongTitle {
            get {
                return ResourceManager.GetString("PasswordConfirmationWrongTitle", resourceCulture);
            }
        }
        
        public static string PasswordSavedMessage {
            get {
                return ResourceManager.GetString("PasswordSavedMessage", resourceCulture);
            }
        }
        
        public static string PasswordSavedTitle {
            get {
                return ResourceManager.GetString("PasswordSavedTitle", resourceCulture);
            }
        }
        
        public static string PasswordWrongMessage {
            get {
                return ResourceManager.GetString("PasswordWrongMessage", resourceCulture);
            }
        }
        
        public static string PasswordWrongTitle {
            get {
                return ResourceManager.GetString("PasswordWrongTitle", resourceCulture);
            }
        }
        
        public static string CategorySummaryLabel {
            get {
                return ResourceManager.GetString("CategorySummaryLabel", resourceCulture);
            }
        }
        
        public static string CategorySpreadingLabel {
            get {
                return ResourceManager.GetString("CategorySpreadingLabel", resourceCulture);
            }
        }
        
        public static string ChargedAccountLabel {
            get {
                return ResourceManager.GetString("ChargedAccountLabel", resourceCulture);
            }
        }
        
        public static string TargetAccountLabel {
            get {
                return ResourceManager.GetString("TargetAccountLabel", resourceCulture);
            }
        }
        
        public static string InvalidEnddateMessage {
            get {
                return ResourceManager.GetString("InvalidEnddateMessage", resourceCulture);
            }
        }
        
        public static string InvalidEnddateTitle {
            get {
                return ResourceManager.GetString("InvalidEnddateTitle", resourceCulture);
            }
        }
        
        public static string NotNowLabel {
            get {
                return ResourceManager.GetString("NotNowLabel", resourceCulture);
            }
        }
        
        public static string RateReminderText {
            get {
                return ResourceManager.GetString("RateReminderText", resourceCulture);
            }
        }
        
        public static string RateReminderTitle {
            get {
                return ResourceManager.GetString("RateReminderTitle", resourceCulture);
            }
        }
        
        public static string BiweeklyLabel {
            get {
                return ResourceManager.GetString("BiweeklyLabel", resourceCulture);
            }
        }
        
        public static string AddCategoryTitle {
            get {
                return ResourceManager.GetString("AddCategoryTitle", resourceCulture);
            }
        }
        
        public static string EditCategoryTitle {
            get {
                return ResourceManager.GetString("EditCategoryTitle", resourceCulture);
            }
        }
        
        public static string CategoriesLabel {
            get {
                return ResourceManager.GetString("CategoriesLabel", resourceCulture);
            }
        }
        
        public static string CashflowDescription {
            get {
                return ResourceManager.GetString("CashflowDescription", resourceCulture);
            }
        }
        
        public static string CategorieSpreadingDescription {
            get {
                return ResourceManager.GetString("CategorieSpreadingDescription", resourceCulture);
            }
        }
        
        public static string CategorySummaryDescription {
            get {
                return ResourceManager.GetString("CategorySummaryDescription", resourceCulture);
            }
        }
        
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        public static string ChooseLabel {
            get {
                return ResourceManager.GetString("ChooseLabel", resourceCulture);
            }
        }
        
        public static string ExpenseHeader {
            get {
                return ResourceManager.GetString("ExpenseHeader", resourceCulture);
            }
        }
        
        public static string IncomeHeader {
            get {
                return ResourceManager.GetString("IncomeHeader", resourceCulture);
            }
        }
        
        public static string TransferHeader {
            get {
                return ResourceManager.GetString("TransferHeader", resourceCulture);
            }
        }
        
        public static string ErrorMessageDelete {
            get {
                return ResourceManager.GetString("ErrorMessageDelete", resourceCulture);
            }
        }
        
        public static string ErrorMessageSave {
            get {
                return ResourceManager.GetString("ErrorMessageSave", resourceCulture);
            }
        }
        
        public static string ErrorTitleDelete {
            get {
                return ResourceManager.GetString("ErrorTitleDelete", resourceCulture);
            }
        }
        
        public static string ChooseCategorieTitle {
            get {
                return ResourceManager.GetString("ChooseCategorieTitle", resourceCulture);
            }
        }
        
        public static string NoNetworkMessage {
            get {
                return ResourceManager.GetString("NoNetworkMessage", resourceCulture);
            }
        }
        
        public static string NoNetworkTitle {
            get {
                return ResourceManager.GetString("NoNetworkTitle", resourceCulture);
            }
        }
        
        public static string GeneralTitle {
            get {
                return ResourceManager.GetString("GeneralTitle", resourceCulture);
            }
        }
        
        public static string DuplicateAccountMessage {
            get {
                return ResourceManager.GetString("DuplicateAccountMessage", resourceCulture);
            }
        }
        
        public static string DuplicateCategoryMessage {
            get {
                return ResourceManager.GetString("DuplicateCategoryMessage", resourceCulture);
            }
        }
        
        public static string DuplicatedNameTitle {
            get {
                return ResourceManager.GetString("DuplicatedNameTitle", resourceCulture);
            }
        }
        
        public static string LoadingLabel {
            get {
                return ResourceManager.GetString("LoadingLabel", resourceCulture);
            }
        }
        
        public static string ErrorMessageAuthenticationFailed {
            get {
                return ResourceManager.GetString("ErrorMessageAuthenticationFailed", resourceCulture);
            }
        }
        
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        public static string ContactLabel {
            get {
                return ResourceManager.GetString("ContactLabel", resourceCulture);
            }
        }
        
        public static string ContributerLabel {
            get {
                return ResourceManager.GetString("ContributerLabel", resourceCulture);
            }
        }
        
        public static string IconDesignerLabel {
            get {
                return ResourceManager.GetString("IconDesignerLabel", resourceCulture);
            }
        }
        
        public static string InfoOpenSource {
            get {
                return ResourceManager.GetString("InfoOpenSource", resourceCulture);
            }
        }
        
        public static string RateLabel {
            get {
                return ResourceManager.GetString("RateLabel", resourceCulture);
            }
        }
        
        public static string TranslationLabel {
            get {
                return ResourceManager.GetString("TranslationLabel", resourceCulture);
            }
        }
        
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        public static string WelcomeLabel {
            get {
                return ResourceManager.GetString("WelcomeLabel", resourceCulture);
            }
        }
        
        public static string NoAccountsMessage {
            get {
                return ResourceManager.GetString("NoAccountsMessage", resourceCulture);
            }
        }
        
        public static string CreateBackupInformationLabel {
            get {
                return ResourceManager.GetString("CreateBackupInformationLabel", resourceCulture);
            }
        }
        
        public static string CreateBackupLabel {
            get {
                return ResourceManager.GetString("CreateBackupLabel", resourceCulture);
            }
        }
        
        public static string LastBackupDateLabel {
            get {
                return ResourceManager.GetString("LastBackupDateLabel", resourceCulture);
            }
        }
        
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        public static string LogoutLabel {
            get {
                return ResourceManager.GetString("LogoutLabel", resourceCulture);
            }
        }
        
        public static string RestoreBackupInformationLabel {
            get {
                return ResourceManager.GetString("RestoreBackupInformationLabel", resourceCulture);
            }
        }
        
        public static string RestoreBackupLabel {
            get {
                return ResourceManager.GetString("RestoreBackupLabel", resourceCulture);
            }
        }
        
        public static string AccountNameLabel {
            get {
                return ResourceManager.GetString("AccountNameLabel", resourceCulture);
            }
        }
        
        public static string CurrentBalanceLabel {
            get {
                return ResourceManager.GetString("CurrentBalanceLabel", resourceCulture);
            }
        }
        
        public static string NoteLabel {
            get {
                return ResourceManager.GetString("NoteLabel", resourceCulture);
            }
        }
        
        public static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }
        
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        public static string EndlessLabel {
            get {
                return ResourceManager.GetString("EndlessLabel", resourceCulture);
            }
        }
        
        public static string RecurringLabel {
            get {
                return ResourceManager.GetString("RecurringLabel", resourceCulture);
            }
        }
        
        public static string EmptyListPlaceholderLabel {
            get {
                return ResourceManager.GetString("EmptyListPlaceholderLabel", resourceCulture);
            }
        }
        
        public static string SearchStringLabel {
            get {
                return ResourceManager.GetString("SearchStringLabel", resourceCulture);
            }
        }
        
        public static string AutobackupInformationLabel {
            get {
                return ResourceManager.GetString("AutobackupInformationLabel", resourceCulture);
            }
        }
        
        public static string AutobackupLabel {
            get {
                return ResourceManager.GetString("AutobackupLabel", resourceCulture);
            }
        }
        
        public static string PasswordActivatedLabel {
            get {
                return ResourceManager.GetString("PasswordActivatedLabel", resourceCulture);
            }
        }
        
        public static string PasswordConfirmationLabel {
            get {
                return ResourceManager.GetString("PasswordConfirmationLabel", resourceCulture);
            }
        }
        
        public static string DeleteRecurringPaymentMessage {
            get {
                return ResourceManager.GetString("DeleteRecurringPaymentMessage", resourceCulture);
            }
        }
        
        public static string DeleteRecurringPaymentTitle {
            get {
                return ResourceManager.GetString("DeleteRecurringPaymentTitle", resourceCulture);
            }
        }
        
        public static string BimonthlyLabel {
            get {
                return ResourceManager.GetString("BimonthlyLabel", resourceCulture);
            }
        }
        
        public static string IsExcludedLabel {
            get {
                return ResourceManager.GetString("IsExcludedLabel", resourceCulture);
            }
        }
        
        public static string PasswordEmptyMessage {
            get {
                return ResourceManager.GetString("PasswordEmptyMessage", resourceCulture);
            }
        }
        
        public static string PasswordEmptyTitle {
            get {
                return ResourceManager.GetString("PasswordEmptyTitle", resourceCulture);
            }
        }
        
        public static string ErrorMessageRestore {
            get {
                return ResourceManager.GetString("ErrorMessageRestore", resourceCulture);
            }
        }
        
        public static string ExcludedAccountsHeader {
            get {
                return ResourceManager.GetString("ExcludedAccountsHeader", resourceCulture);
            }
        }
        
        public static string IncludedAccountsHeader {
            get {
                return ResourceManager.GetString("IncludedAccountsHeader", resourceCulture);
            }
        }
        
        public static string BackupSyncRecurrenceInfoLabel {
            get {
                return ResourceManager.GetString("BackupSyncRecurrenceInfoLabel", resourceCulture);
            }
        }
        
        public static string HourLabel {
            get {
                return ResourceManager.GetString("HourLabel", resourceCulture);
            }
        }
        
        public static string BackupSyncRecurrenceLabel {
            get {
                return ResourceManager.GetString("BackupSyncRecurrenceLabel", resourceCulture);
            }
        }
        
        public static string BiannuallyLabel {
            get {
                return ResourceManager.GetString("BiannuallyLabel", resourceCulture);
            }
        }
        
        public static string QuarterlyLabel {
            get {
                return ResourceManager.GetString("QuarterlyLabel", resourceCulture);
            }
        }
        
        public static string AuthenticationFailedTitle {
            get {
                return ResourceManager.GetString("AuthenticationFailedTitle", resourceCulture);
            }
        }
        
        public static string BackupFailedTitle {
            get {
                return ResourceManager.GetString("BackupFailedTitle", resourceCulture);
            }
        }
        
        public static string BackupRestoreFailedTitle {
            get {
                return ResourceManager.GetString("BackupRestoreFailedTitle", resourceCulture);
            }
        }
        
        public static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        public static string GeneralErrorTitle {
            get {
                return ResourceManager.GetString("GeneralErrorTitle", resourceCulture);
            }
        }
        
        public static string ClearedFilterLabel {
            get {
                return ResourceManager.GetString("ClearedFilterLabel", resourceCulture);
            }
        }
        
        public static string DoneLabel {
            get {
                return ResourceManager.GetString("DoneLabel", resourceCulture);
            }
        }
        
        public static string IsRecurringFilterLabel {
            get {
                return ResourceManager.GetString("IsRecurringFilterLabel", resourceCulture);
            }
        }
        
        public static string SelectFilterTitle {
            get {
                return ResourceManager.GetString("SelectFilterTitle", resourceCulture);
            }
        }
        
        public static string BackupSyncedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("BackupSyncedSuccessfullyMessage", resourceCulture);
            }
        }
        
        public static string BackupSyncFailedMessage {
            get {
                return ResourceManager.GetString("BackupSyncFailedMessage", resourceCulture);
            }
        }
        
        public static string BackgroundAccessDeniedByPolicyMessage {
            get {
                return ResourceManager.GetString("BackgroundAccessDeniedByPolicyMessage", resourceCulture);
            }
        }
        
        public static string BackgroundAccessDeniedByUserMessage {
            get {
                return ResourceManager.GetString("BackgroundAccessDeniedByUserMessage", resourceCulture);
            }
        }
        
        public static string BackgroundAccessDeniedTitle {
            get {
                return ResourceManager.GetString("BackgroundAccessDeniedTitle", resourceCulture);
            }
        }
        
        public static string PassportErrorMessage {
            get {
                return ResourceManager.GetString("PassportErrorMessage", resourceCulture);
            }
        }
        
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        public static string LoginFailedTitle {
            get {
                return ResourceManager.GetString("LoginFailedTitle", resourceCulture);
            }
        }
        
        public static string IsClearedLabel {
            get {
                return ResourceManager.GetString("IsClearedLabel", resourceCulture);
            }
        }
        
        public static string IsRecurringLabel {
            get {
                return ResourceManager.GetString("IsRecurringLabel", resourceCulture);
            }
        }
        
        public static string OthersLabel {
            get {
                return ResourceManager.GetString("OthersLabel", resourceCulture);
            }
        }
        
        public static string AccountsTitle {
            get {
                return ResourceManager.GetString("AccountsTitle", resourceCulture);
            }
        }
        
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        public static string StatisticsTimeRangeTitle {
            get {
                return ResourceManager.GetString("StatisticsTimeRangeTitle", resourceCulture);
            }
        }
        
        public static string CategorySummaryTitle {
            get {
                return ResourceManager.GetString("CategorySummaryTitle", resourceCulture);
            }
        }
        
        public static string NoCategoriesMessage {
            get {
                return ResourceManager.GetString("NoCategoriesMessage", resourceCulture);
            }
        }
        
        public static string NoStatisticItemsMessage {
            get {
                return ResourceManager.GetString("NoStatisticItemsMessage", resourceCulture);
            }
        }
        
        public static string BackupSettingsDescription {
            get {
                return ResourceManager.GetString("BackupSettingsDescription", resourceCulture);
            }
        }
        
        public static string CategoriesSettingsDescription {
            get {
                return ResourceManager.GetString("CategoriesSettingsDescription", resourceCulture);
            }
        }
        
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        public static string AddAccountLabel {
            get {
                return ResourceManager.GetString("AddAccountLabel", resourceCulture);
            }
        }
        
        public static string SaveAccountLabel {
            get {
                return ResourceManager.GetString("SaveAccountLabel", resourceCulture);
            }
        }
        
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        public static string EnddateLabel {
            get {
                return ResourceManager.GetString("EnddateLabel", resourceCulture);
            }
        }
        
        public static string RecurrenceLabel {
            get {
                return ResourceManager.GetString("RecurrenceLabel", resourceCulture);
            }
        }
        
        public static string SavePaymentLabel {
            get {
                return ResourceManager.GetString("SavePaymentLabel", resourceCulture);
            }
        }
        
        public static string NoPaymentsMessage {
            get {
                return ResourceManager.GetString("NoPaymentsMessage", resourceCulture);
            }
        }
        
        public static string SaveCategoryLabel {
            get {
                return ResourceManager.GetString("SaveCategoryLabel", resourceCulture);
            }
        }
        
        public static string AboutSettingsDescription {
            get {
                return ResourceManager.GetString("AboutSettingsDescription", resourceCulture);
            }
        }
        
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        public static string WebsiteLabel {
            get {
                return ResourceManager.GetString("WebsiteLabel", resourceCulture);
            }
        }
        
        public static string BackupTitle {
            get {
                return ResourceManager.GetString("BackupTitle", resourceCulture);
            }
        }
        
        public static string CategoriesTitle {
            get {
                return ResourceManager.GetString("CategoriesTitle", resourceCulture);
            }
        }
        
        public static string SelectCategoryTitle {
            get {
                return ResourceManager.GetString("SelectCategoryTitle", resourceCulture);
            }
        }
        
        public static string CashFlowStatisticTitle {
            get {
                return ResourceManager.GetString("CashFlowStatisticTitle", resourceCulture);
            }
        }
        
        public static string CategorySpreadingTitle {
            get {
                return ResourceManager.GetString("CategorySpreadingTitle", resourceCulture);
            }
        }
        
        public static string CategoryNameLabel {
            get {
                return ResourceManager.GetString("CategoryNameLabel", resourceCulture);
            }
        }
        
        public static string FilterLabel {
            get {
                return ResourceManager.GetString("FilterLabel", resourceCulture);
            }
        }
        
        public static string TimeRangeEndLabel {
            get {
                return ResourceManager.GetString("TimeRangeEndLabel", resourceCulture);
            }
        }
        
        public static string TimeRangeStartLabel {
            get {
                return ResourceManager.GetString("TimeRangeStartLabel", resourceCulture);
            }
        }
        
        public static string SelectDateLabel {
            get {
                return ResourceManager.GetString("SelectDateLabel", resourceCulture);
            }
        }
        
        public static string AddCategoryLabel {
            get {
                return ResourceManager.GetString("AddCategoryLabel", resourceCulture);
            }
        }
        
        public static string SelectStatisticTitel {
            get {
                return ResourceManager.GetString("SelectStatisticTitel", resourceCulture);
            }
        }
        
        public static string BackgroundJobLabel {
            get {
                return ResourceManager.GetString("BackgroundJobLabel", resourceCulture);
            }
        }
        
        public static string BackgroundJobSettingDescription {
            get {
                return ResourceManager.GetString("BackgroundJobSettingDescription", resourceCulture);
            }
        }
        
        public static string BackgroundJobTitle {
            get {
                return ResourceManager.GetString("BackgroundJobTitle", resourceCulture);
            }
        }
        
        public static string PersonalizationTitle {
            get {
                return ResourceManager.GetString("PersonalizationTitle", resourceCulture);
            }
        }
        
        public static string ShortcutsTitle {
            get {
                return ResourceManager.GetString("ShortcutsTitle", resourceCulture);
            }
        }
        
        public static string LiveTileAccountBalance {
            get {
                return ResourceManager.GetString("LiveTileAccountBalance", resourceCulture);
            }
        }
        
        public static string LiveTileAccountName {
            get {
                return ResourceManager.GetString("LiveTileAccountName", resourceCulture);
            }
        }
        
        public static string LiveTileCurrentMonthsExpenses {
            get {
                return ResourceManager.GetString("LiveTileCurrentMonthsExpenses", resourceCulture);
            }
        }
        
        public static string LiveTileLastMonthsExpenses {
            get {
                return ResourceManager.GetString("LiveTileLastMonthsExpenses", resourceCulture);
            }
        }
        
        public static string LiveTilePastPayments {
            get {
                return ResourceManager.GetString("LiveTilePastPayments", resourceCulture);
            }
        }
        
        public static string LiveTileUpcommingPayments {
            get {
                return ResourceManager.GetString("LiveTileUpcommingPayments", resourceCulture);
            }
        }
        
        public static string BalanceLabel {
            get {
                return ResourceManager.GetString("BalanceLabel", resourceCulture);
            }
        }
        
        public static string LastExecutionBackgroundOperationsLabel {
            get {
                return ResourceManager.GetString("LastExecutionBackgroundOperationsLabel", resourceCulture);
            }
        }
        
        public static string LastExecutionClearPaymentLabel {
            get {
                return ResourceManager.GetString("LastExecutionClearPaymentLabel", resourceCulture);
            }
        }
        
        public static string LastExecutionRecurringPaymentLabel {
            get {
                return ResourceManager.GetString("LastExecutionRecurringPaymentLabel", resourceCulture);
            }
        }
        
        public static string LastExecutionSyncBackupLabel {
            get {
                return ResourceManager.GetString("LastExecutionSyncBackupLabel", resourceCulture);
            }
        }
        
        public static string PersonalizationInfoLabel {
            get {
                return ResourceManager.GetString("PersonalizationInfoLabel", resourceCulture);
            }
        }
        
        public static string ThemeDarkLabel {
            get {
                return ResourceManager.GetString("ThemeDarkLabel", resourceCulture);
            }
        }
        
        public static string ThemeLightLabel {
            get {
                return ResourceManager.GetString("ThemeLightLabel", resourceCulture);
            }
        }
        
        public static string SettingsPersonalizationDescription {
            get {
                return ResourceManager.GetString("SettingsPersonalizationDescription", resourceCulture);
            }
        }
        
        public static string SettingsPersonalizationLabel {
            get {
                return ResourceManager.GetString("SettingsPersonalizationLabel", resourceCulture);
            }
        }
        
        public static string LiveTileWideandLargeIncomeFutureText {
            get {
                return ResourceManager.GetString("LiveTileWideandLargeIncomeFutureText", resourceCulture);
            }
        }
        
        public static string LiveTileWideandLargeIncomePastText {
            get {
                return ResourceManager.GetString("LiveTileWideandLargeIncomePastText", resourceCulture);
            }
        }
        
        public static string LiveTileWideandLargePaymentFutureText {
            get {
                return ResourceManager.GetString("LiveTileWideandLargePaymentFutureText", resourceCulture);
            }
        }
        
        public static string LiveTileWideandLargePaymentPastText {
            get {
                return ResourceManager.GetString("LiveTileWideandLargePaymentPastText", resourceCulture);
            }
        }
        
        public static string PintAccountLabel {
            get {
                return ResourceManager.GetString("PintAccountLabel", resourceCulture);
            }
        }
        
        public static string CategorySummaryPlaceHolderLabel {
            get {
                return ResourceManager.GetString("CategorySummaryPlaceHolderLabel", resourceCulture);
            }
        }
        
        public static string MonthlyAverageLabel {
            get {
                return ResourceManager.GetString("MonthlyAverageLabel", resourceCulture);
            }
        }
        
        public static string ContributionsLabel {
            get {
                return ResourceManager.GetString("ContributionsLabel", resourceCulture);
            }
        }
        
        public static string InfoLabel {
            get {
                return ResourceManager.GetString("InfoLabel", resourceCulture);
            }
        }
        
        public static string LeaveFeedbackLabel {
            get {
                return ResourceManager.GetString("LeaveFeedbackLabel", resourceCulture);
            }
        }
        
        public static string ModifyRecurrenceMessage {
            get {
                return ResourceManager.GetString("ModifyRecurrenceMessage", resourceCulture);
            }
        }
        
        public static string ModifyRecurrenceTitle {
            get {
                return ResourceManager.GetString("ModifyRecurrenceTitle", resourceCulture);
            }
        }
    }
}
