//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyFox.Foundation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyFox.Foundation.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support information about this app..
        /// </summary>
        public static string AboutSettingsDescription {
            get {
                return ResourceManager.GetString("AboutSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountNameLabel {
            get {
                return ResourceManager.GetString("AccountNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Account..
        /// </summary>
        public static string AccountRequiredMessage {
            get {
                return ResourceManager.GetString("AccountRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsLabel {
            get {
                return ResourceManager.GetString("AccountsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsTitle {
            get {
                return ResourceManager.GetString("AccountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AddAccountLabel {
            get {
                return ResourceManager.GetString("AddAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string AddAccountTitle {
            get {
                return ResourceManager.GetString("AddAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategoryLabel {
            get {
                return ResourceManager.GetString("AddCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategoryTitle {
            get {
                return ResourceManager.GetString("AddCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string AddExpenseLabel {
            get {
                return ResourceManager.GetString("AddExpenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Expense.
        /// </summary>
        public static string AddExpenseTitle {
            get {
                return ResourceManager.GetString("AddExpenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string AddIncomeLabel {
            get {
                return ResourceManager.GetString("AddIncomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Income.
        /// </summary>
        public static string AddIncomeTitle {
            get {
                return ResourceManager.GetString("AddIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string AddTransferLabel {
            get {
                return ResourceManager.GetString("AddTransferLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Transfer.
        /// </summary>
        public static string AddTransferTitle {
            get {
                return ResourceManager.GetString("AddTransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Fox.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        public static string AuthenticationFailedTitle {
            get {
                return ResourceManager.GetString("AuthenticationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you activate this setting we backup your data automatically to OneDrive. Also we check periodically if something changed on another device..
        /// </summary>
        public static string AutobackupInformationLabel {
            get {
                return ResourceManager.GetString("AutobackupInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically upload and download backups.
        /// </summary>
        public static string AutobackupLabel {
            get {
                return ResourceManager.GetString("AutobackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A system policy denied the permission for the MoneyFox to run in background. Several functions may not work as expected..
        /// </summary>
        public static string BackgroundAccessDeniedByPolicyMessage {
            get {
                return ResourceManager.GetString("BackgroundAccessDeniedByPolicyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You denied the permissions for the MoneyFox to run in the background. Several functions may not work as expected..
        /// </summary>
        public static string BackgroundAccessDeniedByUserMessage {
            get {
                return ResourceManager.GetString("BackgroundAccessDeniedByUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string BackgroundAccessDeniedTitle {
            get {
                return ResourceManager.GetString("BackgroundAccessDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Job.
        /// </summary>
        public static string BackgroundJobLabel {
            get {
                return ResourceManager.GetString("BackgroundJobLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure execution interval for background task..
        /// </summary>
        public static string BackgroundJobSettingDescription {
            get {
                return ResourceManager.GetString("BackgroundJobSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Job.
        /// </summary>
        public static string BackgroundJobTitle {
            get {
                return ResourceManager.GetString("BackgroundJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup failed!.
        /// </summary>
        public static string BackupFailedTitle {
            get {
                return ResourceManager.GetString("BackupFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string BackupLabel {
            get {
                return ResourceManager.GetString("BackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore backup failed!.
        /// </summary>
        public static string BackupRestoreFailedTitle {
            get {
                return ResourceManager.GetString("BackupRestoreFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and restore backups..
        /// </summary>
        public static string BackupSettingsDescription {
            get {
                return ResourceManager.GetString("BackupSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You backup was synced successfully..
        /// </summary>
        public static string BackupSyncedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("BackupSyncedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sync the backup.
        /// </summary>
        public static string BackupSyncFailedMessage {
            get {
                return ResourceManager.GetString("BackupSyncFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the interval to check for changed data..
        /// </summary>
        public static string BackupSyncRecurrenceInfoLabel {
            get {
                return ResourceManager.GetString("BackupSyncRecurrenceInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Recurrence.
        /// </summary>
        public static string BackupSyncRecurrenceLabel {
            get {
                return ResourceManager.GetString("BackupSyncRecurrenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string BackupTitle {
            get {
                return ResourceManager.GetString("BackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string BalanceLabel {
            get {
                return ResourceManager.GetString("BalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biannually.
        /// </summary>
        public static string BiannuallyLabel {
            get {
                return ResourceManager.GetString("BiannuallyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bimonthly.
        /// </summary>
        public static string BimonthlyLabel {
            get {
                return ResourceManager.GetString("BimonthlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biweekly.
        /// </summary>
        public static string BiweeklyLabel {
            get {
                return ResourceManager.GetString("BiweeklyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income, expenses and gains for the selected time period..
        /// </summary>
        public static string CashflowDescription {
            get {
                return ResourceManager.GetString("CashflowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashflow.
        /// </summary>
        public static string CashflowLabel {
            get {
                return ResourceManager.GetString("CashflowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow.
        /// </summary>
        public static string CashFlowStatisticTitle {
            get {
                return ResourceManager.GetString("CashFlowStatisticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesLabel {
            get {
                return ResourceManager.GetString("CategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreading of the expenses to the categories..
        /// </summary>
        public static string CategorieSpreadingDescription {
            get {
                return ResourceManager.GetString("CategorieSpreadingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and modify categories..
        /// </summary>
        public static string CategoriesSettingsDescription {
            get {
                return ResourceManager.GetString("CategoriesSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesTitle {
            get {
                return ResourceManager.GetString("CategoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryNameLabel {
            get {
                return ResourceManager.GetString("CategoryNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Spreading.
        /// </summary>
        public static string CategorySpreadingLabel {
            get {
                return ResourceManager.GetString("CategorySpreadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Spreading.
        /// </summary>
        public static string CategorySpreadingTitle {
            get {
                return ResourceManager.GetString("CategorySpreadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of the categories with a Payment..
        /// </summary>
        public static string CategorySummaryDescription {
            get {
                return ResourceManager.GetString("CategorySummaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Summary.
        /// </summary>
        public static string CategorySummaryLabel {
            get {
                return ResourceManager.GetString("CategorySummaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No statistic items to display. Try to adjust the time range..
        /// </summary>
        public static string CategorySummaryPlaceHolderLabel {
            get {
                return ResourceManager.GetString("CategorySummaryPlaceHolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Summary.
        /// </summary>
        public static string CategorySummaryTitle {
            get {
                return ResourceManager.GetString("CategorySummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You updated a recurring payment. Do you want to update the future Payments aswell?.
        /// </summary>
        public static string ChangeSubsequentPaymentMessage {
            get {
                return ResourceManager.GetString("ChangeSubsequentPaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Recurrence?.
        /// </summary>
        public static string ChangeSubsequentPaymentTitle {
            get {
                return ResourceManager.GetString("ChangeSubsequentPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charged Account.
        /// </summary>
        public static string ChargedAccountLabel {
            get {
                return ResourceManager.GetString("ChargedAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Categorie.
        /// </summary>
        public static string ChooseCategorieTitle {
            get {
                return ResourceManager.GetString("ChooseCategorieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string ChooseLabel {
            get {
                return ResourceManager.GetString("ChooseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared.
        /// </summary>
        public static string ClearedFilterLabel {
            get {
                return ResourceManager.GetString("ClearedFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactLabel {
            get {
                return ResourceManager.GetString("ContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see all contributions head over to GitHub:.
        /// </summary>
        public static string ContributerLabel {
            get {
                return ResourceManager.GetString("ContributerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributions.
        /// </summary>
        public static string ContributionsLabel {
            get {
                return ResourceManager.GetString("ContributionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data will be saved to your OneDrive Account. You’ll find them in a new folder called “MoneyFoxBackupManager”..
        /// </summary>
        public static string CreateBackupInformationLabel {
            get {
                return ResourceManager.GetString("CreateBackupInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Backup.
        /// </summary>
        public static string CreateBackupLabel {
            get {
                return ResourceManager.GetString("CreateBackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance.
        /// </summary>
        public static string CurrentBalanceLabel {
            get {
                return ResourceManager.GetString("CurrentBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string DailyLabel {
            get {
                return ResourceManager.GetString("DailyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily without weekend.
        /// </summary>
        public static string DailyWithoutWeekendLabel {
            get {
                return ResourceManager.GetString("DailyWithoutWeekendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this Account?.
        /// </summary>
        public static string DeleteAccountConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this Category?.
        /// </summary>
        public static string DeleteCategoryConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteCategoryConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this Payment?.
        /// </summary>
        public static string DeletePaymentConfirmationMessage {
            get {
                return ResourceManager.GetString("DeletePaymentConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve deleted a recurring payment. Do you want to delete the recurrence as well?.
        /// </summary>
        public static string DeleteRecurringPaymentMessage {
            get {
                return ResourceManager.GetString("DeleteRecurringPaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Recurrence?.
        /// </summary>
        public static string DeleteRecurringPaymentTitle {
            get {
                return ResourceManager.GetString("DeleteRecurringPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DoneLabel {
            get {
                return ResourceManager.GetString("DoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Account with that name already exists..
        /// </summary>
        public static string DuplicateAccountMessage {
            get {
                return ResourceManager.GetString("DuplicateAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Category with that name already exists..
        /// </summary>
        public static string DuplicateCategoryMessage {
            get {
                return ResourceManager.GetString("DuplicateCategoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already used.
        /// </summary>
        public static string DuplicatedNameTitle {
            get {
                return ResourceManager.GetString("DuplicatedNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        public static string EditAccountTitle {
            get {
                return ResourceManager.GetString("EditAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        public static string EditCategoryTitle {
            get {
                return ResourceManager.GetString("EditCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Income.
        /// </summary>
        public static string EditIncomeTitle {
            get {
                return ResourceManager.GetString("EditIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Expense.
        /// </summary>
        public static string EditSpendingTitle {
            get {
                return ResourceManager.GetString("EditSpendingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Transfer.
        /// </summary>
        public static string EditTransferTitle {
            get {
                return ResourceManager.GetString("EditTransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no categories. Add one by tapping on the plus button at bottom..
        /// </summary>
        public static string EmptyListPlaceholderLabel {
            get {
                return ResourceManager.GetString("EmptyListPlaceholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enddate.
        /// </summary>
        public static string EnddateLabel {
            get {
                return ResourceManager.GetString("EnddateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Endless.
        /// </summary>
        public static string EndlessLabel {
            get {
                return ResourceManager.GetString("EndlessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during the authentication. Please try again later..
        /// </summary>
        public static string ErrorMessageAuthenticationFailed {
            get {
                return ResourceManager.GetString("ErrorMessageAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There where an error while create your backup. Please try again later..
        /// </summary>
        public static string ErrorMessageBackupFailed {
            get {
                return ResourceManager.GetString("ErrorMessageBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while deleting the item..
        /// </summary>
        public static string ErrorMessageDelete {
            get {
                return ResourceManager.GetString("ErrorMessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue during restoring your backup. Please contact us if this error persist..
        /// </summary>
        public static string ErrorMessageRestore {
            get {
                return ResourceManager.GetString("ErrorMessageRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while saving the item..
        /// </summary>
        public static string ErrorMessageSave {
            get {
                return ResourceManager.GetString("ErrorMessageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on delete.
        /// </summary>
        public static string ErrorTitleDelete {
            get {
                return ResourceManager.GetString("ErrorTitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Accounts.
        /// </summary>
        public static string ExcludedAccountsHeader {
            get {
                return ResourceManager.GetString("ExcludedAccountsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add expense.
        /// </summary>
        public static string ExpenseHeader {
            get {
                return ResourceManager.GetString("ExpenseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string ExpenseLabel {
            get {
                return ResourceManager.GetString("ExpenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Money Fox.
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterLabel {
            get {
                return ResourceManager.GetString("FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        public static string GeneralErrorTitle {
            get {
                return ResourceManager.GetString("GeneralErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralTitle {
            get {
                return ResourceManager.GetString("GeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour(s).
        /// </summary>
        public static string HourLabel {
            get {
                return ResourceManager.GetString("HourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app icon was created by:.
        /// </summary>
        public static string IconDesignerLabel {
            get {
                return ResourceManager.GetString("IconDesignerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included Accounts.
        /// </summary>
        public static string IncludedAccountsHeader {
            get {
                return ResourceManager.GetString("IncludedAccountsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add income.
        /// </summary>
        public static string IncomeHeader {
            get {
                return ResourceManager.GetString("IncomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gains.
        /// </summary>
        public static string IncreaseLabel {
            get {
                return ResourceManager.GetString("IncreaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoLabel {
            get {
                return ResourceManager.GetString("InfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an open-source project – and we’d love to work with you! Feel free to contribute.
        ///Tap to visit the Repository:.
        /// </summary>
        public static string InfoOpenSource {
            get {
                return ResourceManager.GetString("InfoOpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enddate of a recurring Payment has to be in the future. Please check your input..
        /// </summary>
        public static string InvalidEnddateMessage {
            get {
                return ResourceManager.GetString("InvalidEnddateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid End Date.
        /// </summary>
        public static string InvalidEnddateTitle {
            get {
                return ResourceManager.GetString("InvalidEnddateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared.
        /// </summary>
        public static string IsClearedLabel {
            get {
                return ResourceManager.GetString("IsClearedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude account from balance.
        /// </summary>
        public static string IsExcludedLabel {
            get {
                return ResourceManager.GetString("IsExcludedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Recurring.
        /// </summary>
        public static string IsRecurringFilterLabel {
            get {
                return ResourceManager.GetString("IsRecurringFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring.
        /// </summary>
        public static string IsRecurringLabel {
            get {
                return ResourceManager.GetString("IsRecurringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, just this.
        /// </summary>
        public static string JustThisLabel {
            get {
                return ResourceManager.GetString("JustThisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Backup created at:.
        /// </summary>
        public static string LastBackupDateLabel {
            get {
                return ResourceManager.GetString("LastBackupDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Executions:.
        /// </summary>
        public static string LastExecutionBackgroundOperationsLabel {
            get {
                return ResourceManager.GetString("LastExecutionBackgroundOperationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paymentclearing:.
        /// </summary>
        public static string LastExecutionClearPaymentLabel {
            get {
                return ResourceManager.GetString("LastExecutionClearPaymentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Recurring Payments:.
        /// </summary>
        public static string LastExecutionRecurringPaymentLabel {
            get {
                return ResourceManager.GetString("LastExecutionRecurringPaymentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Sync:.
        /// </summary>
        public static string LastExecutionSyncBackupLabel {
            get {
                return ResourceManager.GetString("LastExecutionSyncBackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a feedback!.
        /// </summary>
        public static string LeaveFeedbackLabel {
            get {
                return ResourceManager.GetString("LeaveFeedbackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bal. : {0}.
        /// </summary>
        public static string LiveTileAccountBalance {
            get {
                return ResourceManager.GetString("LiveTileAccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account: {0}.
        /// </summary>
        public static string LiveTileAccountName {
            get {
                return ResourceManager.GetString("LiveTileAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string LiveTileCurrentMonthsExpenses {
            get {
                return ResourceManager.GetString("LiveTileCurrentMonthsExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string LiveTileLastMonthsExpenses {
            get {
                return ResourceManager.GetString("LiveTileLastMonthsExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Payments.
        /// </summary>
        public static string LiveTilePastPayments {
            get {
                return ResourceManager.GetString("LiveTilePastPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Payments.
        /// </summary>
        public static string LiveTileUpcommingPayments {
            get {
                return ResourceManager.GetString("LiveTileUpcommingPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will receive {1}.
        /// </summary>
        public static string LiveTileWideandLargeIncomeFutureText {
            get {
                return ResourceManager.GetString("LiveTileWideandLargeIncomeFutureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1}.
        /// </summary>
        public static string LiveTileWideandLargeIncomePastText {
            get {
                return ResourceManager.GetString("LiveTileWideandLargeIncomePastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to be taken from {1}.
        /// </summary>
        public static string LiveTileWideandLargePaymentFutureText {
            get {
                return ResourceManager.GetString("LiveTileWideandLargePaymentFutureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} taken from {1}.
        /// </summary>
        public static string LiveTileWideandLargePaymentPastText {
            get {
                return ResourceManager.GetString("LiveTileWideandLargePaymentPastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingLabel {
            get {
                return ResourceManager.GetString("LoadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t log you in. Please contact us if this issue persists..
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed!.
        /// </summary>
        public static string LoginFailedTitle {
            get {
                return ResourceManager.GetString("LoginFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutLabel {
            get {
                return ResourceManager.GetString("LogoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory field.
        /// </summary>
        public static string MandatoryFieldEmptyTitle {
            get {
                return ResourceManager.GetString("MandatoryFieldEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last year monthly average: .
        /// </summary>
        public static string MonthlyAverageLabel {
            get {
                return ResourceManager.GetString("MonthlyAverageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string MonthlyLabel {
            get {
                return ResourceManager.GetString("MonthlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a name..
        /// </summary>
        public static string NameRequiredMessage {
            get {
                return ResourceManager.GetString("NameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Accounts. Add one by tapping on the plus button at the bottom..
        /// </summary>
        public static string NoAccountsMessage {
            get {
                return ResourceManager.GetString("NoAccountsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no categories to display. Tap the plus button to add one..
        /// </summary>
        public static string NoCategoriesMessage {
            get {
                return ResourceManager.GetString("NoCategoriesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to the internet. Please check your connection and try again..
        /// </summary>
        public static string NoNetworkMessage {
            get {
                return ResourceManager.GetString("NoNetworkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection.
        /// </summary>
        public static string NoNetworkTitle {
            get {
                return ResourceManager.GetString("NoNetworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Payments. Add one by tapping on the plus button at the bottom..
        /// </summary>
        public static string NoPaymentsMessage {
            get {
                return ResourceManager.GetString("NoPaymentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no statistic items in the selected time range..
        /// </summary>
        public static string NoStatisticItemsMessage {
            get {
                return ResourceManager.GetString("NoStatisticItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string NoteLabel {
            get {
                return ResourceManager.GetString("NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Now.
        /// </summary>
        public static string NotNowLabel {
            get {
                return ResourceManager.GetString("NotNowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkLabel {
            get {
                return ResourceManager.GetString("OkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string OthersLabel {
            get {
                return ResourceManager.GetString("OthersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing backups will be overwritten. Do you wanna continue?.
        /// </summary>
        public static string OverwriteBackupMessage {
            get {
                return ResourceManager.GetString("OverwriteBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your local data will be deleted. Are you sure you wanna proceed?.
        /// </summary>
        public static string OverwriteDataMessage {
            get {
                return ResourceManager.GetString("OverwriteDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite?.
        /// </summary>
        public static string OverwriteTitle {
            get {
                return ResourceManager.GetString("OverwriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Passport is not enabled on this device. 
        ///    Please go to settings and enable it!.
        /// </summary>
        public static string PassportErrorMessage {
            get {
                return ResourceManager.GetString("PassportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password protection.
        /// </summary>
        public static string PasswordActivatedLabel {
            get {
                return ResourceManager.GetString("PasswordActivatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation.
        /// </summary>
        public static string PasswordConfirmationLabel {
            get {
                return ResourceManager.GetString("PasswordConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwod and the password confirmation didn&apos;t match. Please check your input..
        /// </summary>
        public static string PasswordConfirmationWrongMessage {
            get {
                return ResourceManager.GetString("PasswordConfirmationWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        public static string PasswordConfirmationWrongTitle {
            get {
                return ResourceManager.GetString("PasswordConfirmationWrongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you&apos;ve entered is empty. Please enter a password first and try again..
        /// </summary>
        public static string PasswordEmptyMessage {
            get {
                return ResourceManager.GetString("PasswordEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty.
        /// </summary>
        public static string PasswordEmptyTitle {
            get {
                return ResourceManager.GetString("PasswordEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was saved succesfully..
        /// </summary>
        public static string PasswordSavedMessage {
            get {
                return ResourceManager.GetString("PasswordSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password saved.
        /// </summary>
        public static string PasswordSavedTitle {
            get {
                return ResourceManager.GetString("PasswordSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you entered was not correct. Please try again..
        /// </summary>
        public static string PasswordWrongMessage {
            get {
                return ResourceManager.GetString("PasswordWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password wrong.
        /// </summary>
        public static string PasswordWrongTitle {
            get {
                return ResourceManager.GetString("PasswordWrongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose between a dark or a light theme. Please restart the app via the task manager to apply your selection..
        /// </summary>
        public static string PersonalizationInfoLabel {
            get {
                return ResourceManager.GetString("PersonalizationInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string PersonalizationTitle {
            get {
                return ResourceManager.GetString("PersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin account to start menu.
        /// </summary>
        public static string PintAccountLabel {
            get {
                return ResourceManager.GetString("PintAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly.
        /// </summary>
        public static string QuarterlyLabel {
            get {
                return ResourceManager.GetString("QuarterlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app!.
        /// </summary>
        public static string RateLabel {
            get {
                return ResourceManager.GetString("RateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you like our app. Support us with a rating in the store.
        ///Do you want to go the the store to rate?.
        /// </summary>
        public static string RateReminderText {
            get {
                return ResourceManager.GetString("RateReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        public static string RateReminderTitle {
            get {
                return ResourceManager.GetString("RateReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence.
        /// </summary>
        public static string RecurrenceLabel {
            get {
                return ResourceManager.GetString("RecurrenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Recurring.
        /// </summary>
        public static string RecurringLabel {
            get {
                return ResourceManager.GetString("RecurringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the previous uploaded database backup and replace your local data with it.
        ///WARNING: Local changes you made meanwhile will be lost!.
        /// </summary>
        public static string RestoreBackupInformationLabel {
            get {
                return ResourceManager.GetString("RestoreBackupInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Backup.
        /// </summary>
        public static string RestoreBackupLabel {
            get {
                return ResourceManager.GetString("RestoreBackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string RevenueLabel {
            get {
                return ResourceManager.GetString("RevenueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Account.
        /// </summary>
        public static string SaveAccountLabel {
            get {
                return ResourceManager.GetString("SaveAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Category.
        /// </summary>
        public static string SaveCategoryLabel {
            get {
                return ResourceManager.GetString("SaveCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Payment.
        /// </summary>
        public static string SavePaymentLabel {
            get {
                return ResourceManager.GetString("SavePaymentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchStringLabel {
            get {
                return ResourceManager.GetString("SearchStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string SecurityTitle {
            get {
                return ResourceManager.GetString("SecurityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string SelectCategoryTitle {
            get {
                return ResourceManager.GetString("SelectCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string SelectDateLabel {
            get {
                return ResourceManager.GetString("SelectDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string SelectDateTitle {
            get {
                return ResourceManager.GetString("SelectDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Filter.
        /// </summary>
        public static string SelectFilterTitle {
            get {
                return ResourceManager.GetString("SelectFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select operation.
        /// </summary>
        public static string SelectOperationLabel {
            get {
                return ResourceManager.GetString("SelectOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Statistic.
        /// </summary>
        public static string SelectStatisticTitel {
            get {
                return ResourceManager.GetString("SelectStatisticTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your prefered Theme..
        /// </summary>
        public static string SettingsPersonalizationDescription {
            get {
                return ResourceManager.GetString("SettingsPersonalizationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPersonalizationLabel {
            get {
                return ResourceManager.GetString("SettingsPersonalizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string ShortcutsTitle {
            get {
                return ResourceManager.GetString("ShortcutsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsLabel {
            get {
                return ResourceManager.GetString("StatisticsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Range:.
        /// </summary>
        public static string StatisticsTimeRangeTitle {
            get {
                return ResourceManager.GetString("StatisticsTimeRangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsTitle {
            get {
                return ResourceManager.GetString("StatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Account.
        /// </summary>
        public static string TargetAccountLabel {
            get {
                return ResourceManager.GetString("TargetAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task was successful completed..
        /// </summary>
        public static string TaskSuccessfulMessage {
            get {
                return ResourceManager.GetString("TaskSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeDarkLabel {
            get {
                return ResourceManager.GetString("ThemeDarkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeLightLabel {
            get {
                return ResourceManager.GetString("ThemeLightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Range End.
        /// </summary>
        public static string TimeRangeEndLabel {
            get {
                return ResourceManager.GetString("TimeRangeEndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Range Start.
        /// </summary>
        public static string TimeRangeStartLabel {
            get {
                return ResourceManager.GetString("TimeRangeStartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add transfer.
        /// </summary>
        public static string TransferHeader {
            get {
                return ResourceManager.GetString("TransferHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is something not properly translated or not translated at all? Help us! Head over to crowdin and help improve the Money Fox:.
        /// </summary>
        public static string TranslationLabel {
            get {
                return ResourceManager.GetString("TranslationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, update All.
        /// </summary>
        public static string UpdateAllLabel {
            get {
                return ResourceManager.GetString("UpdateAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string WebsiteLabel {
            get {
                return ResourceManager.GetString("WebsiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string WeeklyLabel {
            get {
                return ResourceManager.GetString("WeeklyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string WelcomeLabel {
            get {
                return ResourceManager.GetString("WelcomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string YearlyLabel {
            get {
                return ResourceManager.GetString("YearlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
    }
}
