//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyFox.Foundation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyFox.Foundation.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string AboutViewModel_ContactLabel {
            get {
                return ResourceManager.GetString("AboutViewModel.ContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see all contributions head over to GitHub:.
        /// </summary>
        public static string AboutViewModel_ContributerLabel {
            get {
                return ResourceManager.GetString("AboutViewModel.ContributerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app icon was created by:.
        /// </summary>
        public static string AboutViewModel_IconDesignerLabel {
            get {
                return ResourceManager.GetString("AboutViewModel.IconDesignerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an open-source project – and we’d love to work with you! Feel free to contribute.
        ///Tap to visit the Repository:.
        /// </summary>
        public static string AboutViewModel_InfoOpenSource {
            get {
                return ResourceManager.GetString("AboutViewModel.InfoOpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate us!.
        /// </summary>
        public static string AboutViewModel_RateLabel {
            get {
                return ResourceManager.GetString("AboutViewModel.RateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is something not properly translated or not translated at all? Help us! Head over to crowdin and help improve the Money Fox:.
        /// </summary>
        public static string AboutViewModel_TranslationLabel {
            get {
                return ResourceManager.GetString("AboutViewModel.TranslationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AboutViewModel_VersionLabel {
            get {
                return ResourceManager.GetString("AboutViewModel.VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Accounts. Add one by tapping on the plus button at the bottom..
        /// </summary>
        public static string AccountListViewModel_EmptyListPlaceholderLabel {
            get {
                return ResourceManager.GetString("AccountListViewModel.EmptyListPlaceholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Accounts.
        /// </summary>
        public static string AccountListViewModel_ExcludedAccountsHeader {
            get {
                return ResourceManager.GetString("AccountListViewModel.ExcludedAccountsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included Accounts.
        /// </summary>
        public static string AccountListViewModel_IncludedAccountsHeader {
            get {
                return ResourceManager.GetString("AccountListViewModel.IncludedAccountsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Account..
        /// </summary>
        public static string AccountRequiredMessage {
            get {
                return ResourceManager.GetString("AccountRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsLabel {
            get {
                return ResourceManager.GetString("AccountsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string AddAccountTitle {
            get {
                return ResourceManager.GetString("AddAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategoryTitle {
            get {
                return ResourceManager.GetString("AddCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Expense.
        /// </summary>
        public static string AddExpenseLabel {
            get {
                return ResourceManager.GetString("AddExpenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Expense.
        /// </summary>
        public static string AddExpenseTitle {
            get {
                return ResourceManager.GetString("AddExpenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Income.
        /// </summary>
        public static string AddIncomeLabel {
            get {
                return ResourceManager.GetString("AddIncomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Income.
        /// </summary>
        public static string AddIncomeTitle {
            get {
                return ResourceManager.GetString("AddIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Transfer.
        /// </summary>
        public static string AddTransferLabel {
            get {
                return ResourceManager.GetString("AddTransferLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Transfer.
        /// </summary>
        public static string AddTransferTitle {
            get {
                return ResourceManager.GetString("AddTransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Fox.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        public static string AuthenticationFailedTitle {
            get {
                return ResourceManager.GetString("AuthenticationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A system policy denied the permission for the MoneyFox to run in background. Several functions may not work as expected..
        /// </summary>
        public static string BackgroundAccessDeniedByPolicyMessage {
            get {
                return ResourceManager.GetString("BackgroundAccessDeniedByPolicyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You denied the permissions for the MoneyFox to run in the background. Several functions may not work as expected..
        /// </summary>
        public static string BackgroundAccessDeniedByUserMessage {
            get {
                return ResourceManager.GetString("BackgroundAccessDeniedByUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string BackgroundAccessDeniedTitle {
            get {
                return ResourceManager.GetString("BackgroundAccessDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup failed!.
        /// </summary>
        public static string BackupFailedTitle {
            get {
                return ResourceManager.GetString("BackupFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string BackupLabel {
            get {
                return ResourceManager.GetString("BackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore backup failed!.
        /// </summary>
        public static string BackupRestoreFailedTitle {
            get {
                return ResourceManager.GetString("BackupRestoreFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You backup was synced successfully..
        /// </summary>
        public static string BackupSyncedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("BackupSyncedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sync the backup.
        /// </summary>
        public static string BackupSyncFailedMessage {
            get {
                return ResourceManager.GetString("BackupSyncFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data will be saved to your OneDrive Account. You’ll find them in a new folder called “MoneyFoxBackupManager”..
        /// </summary>
        public static string BackupViewModel_CreateBackupInformationLabel {
            get {
                return ResourceManager.GetString("BackupViewModel.CreateBackupInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Backup.
        /// </summary>
        public static string BackupViewModel_CreateBackupLabel {
            get {
                return ResourceManager.GetString("BackupViewModel.CreateBackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Backup created at:.
        /// </summary>
        public static string BackupViewModel_LastBackupDateLabel {
            get {
                return ResourceManager.GetString("BackupViewModel.LastBackupDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string BackupViewModel_LoginLabel {
            get {
                return ResourceManager.GetString("BackupViewModel.LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string BackupViewModel_LogoutLabel {
            get {
                return ResourceManager.GetString("BackupViewModel.LogoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the previous uploaded database backup and replace your local data with it.
        ///WARNING: Local changes you made meanwhile will be lost!.
        /// </summary>
        public static string BackupViewModel_RestoreBackupInformationLabel {
            get {
                return ResourceManager.GetString("BackupViewModel.RestoreBackupInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Backup.
        /// </summary>
        public static string BackupViewModel_RestoreBackupLabel {
            get {
                return ResourceManager.GetString("BackupViewModel.RestoreBackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biannually.
        /// </summary>
        public static string BiannuallyLabel {
            get {
                return ResourceManager.GetString("BiannuallyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bimonthly.
        /// </summary>
        public static string BimonthlyLabel {
            get {
                return ResourceManager.GetString("BimonthlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biweekly.
        /// </summary>
        public static string BiweeklyLabel {
            get {
                return ResourceManager.GetString("BiweeklyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income, expenses and gains for the selected time period..
        /// </summary>
        public static string CashflowDescription {
            get {
                return ResourceManager.GetString("CashflowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashflow.
        /// </summary>
        public static string CashflowLabel {
            get {
                return ResourceManager.GetString("CashflowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesLabel {
            get {
                return ResourceManager.GetString("CategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreading of the expenses to the categories..
        /// </summary>
        public static string CategorieSpreadingDescription {
            get {
                return ResourceManager.GetString("CategorieSpreadingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no categories. Add one by tapping on the plus button at bottom..
        /// </summary>
        public static string CategoryListViewModel_EmptyListPlaceholderLabel {
            get {
                return ResourceManager.GetString("CategoryListViewModel.EmptyListPlaceholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string CategoryListViewModel_SearchStringLabel {
            get {
                return ResourceManager.GetString("CategoryListViewModel.SearchStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Spreading.
        /// </summary>
        public static string CategorySpreadingLabel {
            get {
                return ResourceManager.GetString("CategorySpreadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of the categories with a Payment..
        /// </summary>
        public static string CategorySummaryDescription {
            get {
                return ResourceManager.GetString("CategorySummaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Summary.
        /// </summary>
        public static string CategorySummaryLabel {
            get {
                return ResourceManager.GetString("CategorySummaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You updated a recurring payment. Do you want to update the future Payments aswell?.
        /// </summary>
        public static string ChangeSubsequentPaymentMessage {
            get {
                return ResourceManager.GetString("ChangeSubsequentPaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Recurrence?.
        /// </summary>
        public static string ChangeSubsequentPaymentTitle {
            get {
                return ResourceManager.GetString("ChangeSubsequentPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charged Account.
        /// </summary>
        public static string ChargedAccountLabel {
            get {
                return ResourceManager.GetString("ChargedAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Categorie.
        /// </summary>
        public static string ChooseCategorieTitle {
            get {
                return ResourceManager.GetString("ChooseCategorieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string ChooseLabel {
            get {
                return ResourceManager.GetString("ChooseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared.
        /// </summary>
        public static string ClearedFilterLabel {
            get {
                return ResourceManager.GetString("ClearedFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing payments failed!.
        /// </summary>
        public static string ClearPaymentFailedMessage {
            get {
                return ResourceManager.GetString("ClearPaymentFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished clearing your payments..
        /// </summary>
        public static string ClearPaymentFinishedMessage {
            get {
                return ResourceManager.GetString("ClearPaymentFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create recurring payments!.
        /// </summary>
        public static string CreateRecurringPaymentFailedMessage {
            get {
                return ResourceManager.GetString("CreateRecurringPaymentFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string DailyLabel {
            get {
                return ResourceManager.GetString("DailyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily without weekend.
        /// </summary>
        public static string DailyWithoutWeekendLabel {
            get {
                return ResourceManager.GetString("DailyWithoutWeekendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this Account?.
        /// </summary>
        public static string DeleteAccountConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this Category?.
        /// </summary>
        public static string DeleteCategoryConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteCategoryConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this Payment?.
        /// </summary>
        public static string DeletePaymentConfirmationMessage {
            get {
                return ResourceManager.GetString("DeletePaymentConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve deleted a recurring payment. Do you want to delete the recurrence as well?.
        /// </summary>
        public static string DeleteRecurringPaymentMessage {
            get {
                return ResourceManager.GetString("DeleteRecurringPaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Recurrence?.
        /// </summary>
        public static string DeleteRecurringPaymentTitle {
            get {
                return ResourceManager.GetString("DeleteRecurringPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DoneLabel {
            get {
                return ResourceManager.GetString("DoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Account with that name already exists..
        /// </summary>
        public static string DuplicateAccountMessage {
            get {
                return ResourceManager.GetString("DuplicateAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Category with that name already exists..
        /// </summary>
        public static string DuplicateCategoryMessage {
            get {
                return ResourceManager.GetString("DuplicateCategoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already used.
        /// </summary>
        public static string DuplicatedNameTitle {
            get {
                return ResourceManager.GetString("DuplicatedNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        public static string EditAccountTitle {
            get {
                return ResourceManager.GetString("EditAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        public static string EditCategoryTitle {
            get {
                return ResourceManager.GetString("EditCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Income.
        /// </summary>
        public static string EditIncomeTitle {
            get {
                return ResourceManager.GetString("EditIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Expense.
        /// </summary>
        public static string EditSpendingTitle {
            get {
                return ResourceManager.GetString("EditSpendingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Transfer.
        /// </summary>
        public static string EditTransferTitle {
            get {
                return ResourceManager.GetString("EditTransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during the authentication. Please try again later..
        /// </summary>
        public static string ErrorMessageAuthenticationFailed {
            get {
                return ResourceManager.GetString("ErrorMessageAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There where an error while create your backup. Please try again later..
        /// </summary>
        public static string ErrorMessageBackupFailed {
            get {
                return ResourceManager.GetString("ErrorMessageBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while deleting the item..
        /// </summary>
        public static string ErrorMessageDelete {
            get {
                return ResourceManager.GetString("ErrorMessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue during restoring your backup. Please contact us if this error persist..
        /// </summary>
        public static string ErrorMessageRestore {
            get {
                return ResourceManager.GetString("ErrorMessageRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while saving the item..
        /// </summary>
        public static string ErrorMessageSave {
            get {
                return ResourceManager.GetString("ErrorMessageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on delete.
        /// </summary>
        public static string ErrorTitleDelete {
            get {
                return ResourceManager.GetString("ErrorTitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add expense.
        /// </summary>
        public static string ExpenseHeader {
            get {
                return ResourceManager.GetString("ExpenseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string ExpenseLabel {
            get {
                return ResourceManager.GetString("ExpenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Money Fox.
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        public static string GeneralErrorTitle {
            get {
                return ResourceManager.GetString("GeneralErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralTitle {
            get {
                return ResourceManager.GetString("GeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add income.
        /// </summary>
        public static string IncomeHeader {
            get {
                return ResourceManager.GetString("IncomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gains.
        /// </summary>
        public static string IncreaseLabel {
            get {
                return ResourceManager.GetString("IncreaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enddate of a recurring Payment has to be in the future. Please check your input..
        /// </summary>
        public static string InvalidEnddateMessage {
            get {
                return ResourceManager.GetString("InvalidEnddateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid End Date.
        /// </summary>
        public static string InvalidEnddateTitle {
            get {
                return ResourceManager.GetString("InvalidEnddateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Recurring.
        /// </summary>
        public static string IsRecurringFilterLabel {
            get {
                return ResourceManager.GetString("IsRecurringFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, just this.
        /// </summary>
        public static string JustThisLabel {
            get {
                return ResourceManager.GetString("JustThisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingLabel {
            get {
                return ResourceManager.GetString("LoadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t log you in. Please contact us if this issue persists..
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed!.
        /// </summary>
        public static string LoginFailedTitle {
            get {
                return ResourceManager.GetString("LoginFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginViewModel_LoginLabel {
            get {
                return ResourceManager.GetString("LoginViewModel.LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginViewModel_PasswordLabel {
            get {
                return ResourceManager.GetString("LoginViewModel.PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string LoginViewModel_WelcomeLabel {
            get {
                return ResourceManager.GetString("LoginViewModel.WelcomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory field.
        /// </summary>
        public static string MandatoryFieldEmptyTitle {
            get {
                return ResourceManager.GetString("MandatoryFieldEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuViewModel_AboutLabel {
            get {
                return ResourceManager.GetString("MenuViewModel.AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string MenuViewModel_AccountsLabel {
            get {
                return ResourceManager.GetString("MenuViewModel.AccountsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string MenuViewModel_AddLabel {
            get {
                return ResourceManager.GetString("MenuViewModel.AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string MenuViewModel_BackupLabel {
            get {
                return ResourceManager.GetString("MenuViewModel.BackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string MenuViewModel_CategoriesLabel {
            get {
                return ResourceManager.GetString("MenuViewModel.CategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MenuViewModel_DeleteLabel {
            get {
                return ResourceManager.GetString("MenuViewModel.DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuViewModel_SaveLabel {
            get {
                return ResourceManager.GetString("MenuViewModel.SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuViewModel_SettingsLabel {
            get {
                return ResourceManager.GetString("MenuViewModel.SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A way to make budgeting easy..
        /// </summary>
        public static string MenuViewModel_SloganLabel {
            get {
                return ResourceManager.GetString("MenuViewModel.SloganLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string MenuViewModel_StatisticsLabel {
            get {
                return ResourceManager.GetString("MenuViewModel.StatisticsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string ModifyAccountViewModel_AccountNameLabel {
            get {
                return ResourceManager.GetString("ModifyAccountViewModel.AccountNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance.
        /// </summary>
        public static string ModifyAccountViewModel_CurrentBalanceLabel {
            get {
                return ResourceManager.GetString("ModifyAccountViewModel.CurrentBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iban.
        /// </summary>
        public static string ModifyAccountViewModel_IbanLabel {
            get {
                return ResourceManager.GetString("ModifyAccountViewModel.IbanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude account from balance.
        /// </summary>
        public static string ModifyAccountViewModel_IsExcludedLabel {
            get {
                return ResourceManager.GetString("ModifyAccountViewModel.IsExcludedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string ModifyAccountViewModel_NoteLabel {
            get {
                return ResourceManager.GetString("ModifyAccountViewModel.NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string ModifyCategoryViewModel_CategoryNameLabel {
            get {
                return ResourceManager.GetString("ModifyCategoryViewModel.CategoryNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string ModifyCategoryViewModel_NoteLabel {
            get {
                return ResourceManager.GetString("ModifyCategoryViewModel.NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string ModifyPaymentViewModel_AmountLabel {
            get {
                return ResourceManager.GetString("ModifyPaymentViewModel.AmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ModifyPaymentViewModel_CategoryLabel {
            get {
                return ResourceManager.GetString("ModifyPaymentViewModel.CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ModifyPaymentViewModel_DateLabel {
            get {
                return ResourceManager.GetString("ModifyPaymentViewModel.DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Endless.
        /// </summary>
        public static string ModifyPaymentViewModel_EndlessLabel {
            get {
                return ResourceManager.GetString("ModifyPaymentViewModel.EndlessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string ModifyPaymentViewModel_NoteLabel {
            get {
                return ResourceManager.GetString("ModifyPaymentViewModel.NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Recurring.
        /// </summary>
        public static string ModifyPaymentViewModel_RecurringLabel {
            get {
                return ResourceManager.GetString("ModifyPaymentViewModel.RecurringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string MonthlyLabel {
            get {
                return ResourceManager.GetString("MonthlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a name..
        /// </summary>
        public static string NameRequiredMessage {
            get {
                return ResourceManager.GetString("NameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to the internet. Please check your connection and try again..
        /// </summary>
        public static string NoNetworkMessage {
            get {
                return ResourceManager.GetString("NoNetworkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection.
        /// </summary>
        public static string NoNetworkTitle {
            get {
                return ResourceManager.GetString("NoNetworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Now.
        /// </summary>
        public static string NotNowLabel {
            get {
                return ResourceManager.GetString("NotNowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkLabel {
            get {
                return ResourceManager.GetString("OkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing backups will be overwritten. Do you wanna continue?.
        /// </summary>
        public static string OverwriteBackupMessage {
            get {
                return ResourceManager.GetString("OverwriteBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your local data will be deleted. Are you sure you wanna proceed?.
        /// </summary>
        public static string OverwriteDataMessage {
            get {
                return ResourceManager.GetString("OverwriteDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite?.
        /// </summary>
        public static string OverwriteTitle {
            get {
                return ResourceManager.GetString("OverwriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Passport is not enabled on this device. 
        ///    Please go to settings and enable it!.
        /// </summary>
        public static string PassportErrorMessage {
            get {
                return ResourceManager.GetString("PassportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwod and the password confirmation didn&apos;t match. Please check your input..
        /// </summary>
        public static string PasswordConfirmationWrongMessage {
            get {
                return ResourceManager.GetString("PasswordConfirmationWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        public static string PasswordConfirmationWrongTitle {
            get {
                return ResourceManager.GetString("PasswordConfirmationWrongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you&apos;ve entered is empty. Please enter a password first and try again..
        /// </summary>
        public static string PasswordEmptyMessage {
            get {
                return ResourceManager.GetString("PasswordEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty.
        /// </summary>
        public static string PasswordEmptyTitle {
            get {
                return ResourceManager.GetString("PasswordEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was saved succesfully..
        /// </summary>
        public static string PasswordSavedMessage {
            get {
                return ResourceManager.GetString("PasswordSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password saved.
        /// </summary>
        public static string PasswordSavedTitle {
            get {
                return ResourceManager.GetString("PasswordSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you entered was not correct. Please try again..
        /// </summary>
        public static string PasswordWrongMessage {
            get {
                return ResourceManager.GetString("PasswordWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password wrong.
        /// </summary>
        public static string PasswordWrongTitle {
            get {
                return ResourceManager.GetString("PasswordWrongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Payments. Add one by tapping on the plus button at the bottom..
        /// </summary>
        public static string PaymentListViewModel_EmptyListPlaceholderLabel {
            get {
                return ResourceManager.GetString("PaymentListViewModel.EmptyListPlaceholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly.
        /// </summary>
        public static string QuarterlyLabel {
            get {
                return ResourceManager.GetString("QuarterlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you like our app. Support us with a rating in the store.
        ///Do you want to go the the store to rate?.
        /// </summary>
        public static string RateReminderText {
            get {
                return ResourceManager.GetString("RateReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        public static string RateReminderTitle {
            get {
                return ResourceManager.GetString("RateReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring payments where created..
        /// </summary>
        public static string RecurringPaymentsCreatedMessages {
            get {
                return ResourceManager.GetString("RecurringPaymentsCreatedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string RevenueLabel {
            get {
                return ResourceManager.GetString("RevenueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string SecurityTitle {
            get {
                return ResourceManager.GetString("SecurityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SelectCategoryListViewModel_SearchStringLabel {
            get {
                return ResourceManager.GetString("SelectCategoryListViewModel.SearchStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string SelectDateTitle {
            get {
                return ResourceManager.GetString("SelectDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared.
        /// </summary>
        public static string SelectFilterDialogViewModel_IsClearedLabel {
            get {
                return ResourceManager.GetString("SelectFilterDialogViewModel.IsClearedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring.
        /// </summary>
        public static string SelectFilterDialogViewModel_IsRecurringLabel {
            get {
                return ResourceManager.GetString("SelectFilterDialogViewModel.IsRecurringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Filter.
        /// </summary>
        public static string SelectFilterDialogViewModel_SelectFilterLabel {
            get {
                return ResourceManager.GetString("SelectFilterDialogViewModel.SelectFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Filter.
        /// </summary>
        public static string SelectFilterTitle {
            get {
                return ResourceManager.GetString("SelectFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select operation.
        /// </summary>
        public static string SelectOperationLabel {
            get {
                return ResourceManager.GetString("SelectOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you activate this setting after every change on the database a backup is made to OneDrive. Also if you launch the application there it will check if there are newer backups and restore it if so..
        /// </summary>
        public static string SettingsGeneralViewModel_AutobackupInformationLabel {
            get {
                return ResourceManager.GetString("SettingsGeneralViewModel.AutobackupInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically upload and download backups.
        /// </summary>
        public static string SettingsGeneralViewModel_AutobackupLabel {
            get {
                return ResourceManager.GetString("SettingsGeneralViewModel.AutobackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the amount of hours to sync the backup..
        /// </summary>
        public static string SettingsGeneralViewModel_BackupSyncRecurrenceInfoLabel {
            get {
                return ResourceManager.GetString("SettingsGeneralViewModel.BackupSyncRecurrenceInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Recurrence.
        /// </summary>
        public static string SettingsGeneralViewModel_BackupSyncRecurrenceLabel {
            get {
                return ResourceManager.GetString("SettingsGeneralViewModel.BackupSyncRecurrenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour(s).
        /// </summary>
        public static string SettingsGeneralViewModel_HourLabel {
            get {
                return ResourceManager.GetString("SettingsGeneralViewModel.HourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string SettingsSecurityViewModel_DoneLabel {
            get {
                return ResourceManager.GetString("SettingsSecurityViewModel.DoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password protection.
        /// </summary>
        public static string SettingsSecurityViewModel_PasswordActivatedLabel {
            get {
                return ResourceManager.GetString("SettingsSecurityViewModel.PasswordActivatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation.
        /// </summary>
        public static string SettingsSecurityViewModel_PasswordConfirmationLabel {
            get {
                return ResourceManager.GetString("SettingsSecurityViewModel.PasswordConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SettingsSecurityViewModel_PasswordLabel {
            get {
                return ResourceManager.GetString("SettingsSecurityViewModel.PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsLabel {
            get {
                return ResourceManager.GetString("StatisticsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic.
        /// </summary>
        public static string StatisticTitle {
            get {
                return ResourceManager.GetString("StatisticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Account.
        /// </summary>
        public static string TargetAccountLabel {
            get {
                return ResourceManager.GetString("TargetAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task was successful completed..
        /// </summary>
        public static string TaskSuccessfulMessage {
            get {
                return ResourceManager.GetString("TaskSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add transfer.
        /// </summary>
        public static string TransferHeader {
            get {
                return ResourceManager.GetString("TransferHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, update All.
        /// </summary>
        public static string UpdateAllLabel {
            get {
                return ResourceManager.GetString("UpdateAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string WeeklyLabel {
            get {
                return ResourceManager.GetString("WeeklyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string YearlyLabel {
            get {
                return ResourceManager.GetString("YearlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
    }
}
